Add kernelCTF CVE-2024-0193_lts
google/security-research pull request #102
Opened 2024-05-17 02:53 UTC by kevinrich1337

2024-05-30 10:06 UTC, chanijindal1 requested changes
Hi! Please reference the comments from here for the required changes
https://github.com/google/security-research/pull/100#pullrequestreview-2085256469

2024-05-30 13:43 UTC, chanijindal1 reviewed
+1 comment

2024-05-30 13:43 UTC, chanijindal1 commented on pocs/linux/kernelctf/CVE-2024-0193_lts/docs/exploit.md
> +    // current->rcu_read_lock_nesting = 0 (Bypass rcu protected section)
Why is rcu bypass needed here?

2024-06-10 07:18 UTC, kevinrich1337 commented
> Hi! Please reference the comments from here for the required changes [#100 (review)](https://github.com/google/security-research/pull/100#pullrequestreview-2085256469)

Hello, @chanijindal1

I've updated exploit.md and exploit.c based on the comments.

Please check it.

Thanks.

2024-06-10 07:22 UTC, kevinrich1337 commented on pocs/linux/kernelctf/CVE-2024-0193_lts/docs/exploit.md
> +    // current->rcu_read_lock_nesting = 0 (Bypass rcu protected section)
Because ROP-chain is executed in a RCU read-side critical section. The technique is suggested in the write-up [CVE-2023-0461_mitigation](https://github.com/google/security-research/blob/master/pocs/linux/kernelctf/CVE-2023-0461_mitigation/docs/novel-techniques.md).

2024-06-21 17:56 UTC, chanijindal1 commented on pocs/linux/kernelctf/CVE-2024-0193_lts/docs/exploit.md
> +    // current->rcu_read_lock_nesting = 0 (Bypass rcu protected section)
Could you add a comment about that in the exploit so that it's clear

2024-06-21 17:57 UTC, chanijindal1 commented
Changes look good. Requested to add a comment about the RCU technique as well.

2024-06-26 09:12 UTC, kevinrich1337 commented
> Changes look good. Requested to add a comment about the RCU technique as well.

Hello, @chanijindal1

I added the requested comment to exploit.c.

2024-06-27 21:15 UTC, merged