Add kernelCTF CVE-2024-0193_cos
google/security-research pull request #103
Opened 2024-05-17 08:40 UTC by kevinrich1337

2024-05-30 13:29 UTC, chanijindal1 requested changes
Hi!
Comments from  https://github.com/google/security-research/pull/100#pullrequestreview-2085256469 apply.

Also added added additional comments.

2024-05-30 13:29 UTC, chanijindal1 commented on pocs/linux/kernelctf/CVE-2024-0193_cos/exploit/cos-105-17412.226.52/exploit.c
> +    nftnl_set_set_u32(set2, NFTNL_SET_KEY_LEN, set_ksize);
Could you explain what  NFTNL_SET_KEY_TYPE was being used for and why was it removed?

2024-05-30 13:29 UTC, chanijindal1 commented on pocs/linux/kernelctf/CVE-2024-0193_cos/exploit/cos-105-17412.226.52/exploit.c
> +    nftnl_set_set_data(set2, NFTNL_SET_DESC_CONCAT, desc_concat, 10);
Why is NFTNL_SET_GC_INTERVAL not needed anymore?

2024-05-30 13:29 UTC, chanijindal1 commented on pocs/linux/kernelctf/CVE-2024-0193_cos/exploit/cos-105-17412.226.52/exploit.c
> +    nftnl_rule_set_u64(rule_del, NFTNL_RULE_HANDLE, 0x1109);
Looks like the size of NFTNL_RULE_HANDLE was changed from 0x1019 to 0x1109. Could you explain why?

2024-05-30 13:29 UTC, chanijindal1 commented on pocs/linux/kernelctf/CVE-2024-0193_cos/exploit/cos-105-17412.226.52/exploit.c
> +#define TABLE_SPRAY 0x200
Looks like the number of objects being sprayed increased compared to the previous exploits. Was this for optimization or a different reason?

2024-06-10 07:39 UTC, kevinrich1337 commented on pocs/linux/kernelctf/CVE-2024-0193_cos/exploit/cos-105-17412.226.52/exploit.c
> +    nftnl_set_set_u32(set2, NFTNL_SET_KEY_LEN, set_ksize);
I removed it because the flag is irrelevant to the exploit.

2024-06-10 07:39 UTC, kevinrich1337 commented on pocs/linux/kernelctf/CVE-2024-0193_cos/exploit/cos-105-17412.226.52/exploit.c
> +    nftnl_set_set_data(set2, NFTNL_SET_DESC_CONCAT, desc_concat, 10);
I removed it because the flag is irrelevant to the exploit.

2024-06-10 07:41 UTC, kevinrich1337 commented on pocs/linux/kernelctf/CVE-2024-0193_cos/exploit/cos-105-17412.226.52/exploit.c
> +#define TABLE_SPRAY 0x200
Due to the different target kernel versions, I used different number of spray for optimization.

2024-06-10 07:45 UTC, kevinrich1337 commented on pocs/linux/kernelctf/CVE-2024-0193_cos/exploit/cos-105-17412.226.52/exploit.c
> +    nftnl_rule_set_u64(rule_del, NFTNL_RULE_HANDLE, 0x1109);
This is because I used different `SET_SPRAY`, which affects the handle value, for optimizing.

2024-06-10 07:46 UTC, kevinrich1337 commented
> Hi! Comments from [#100 (review)](https://github.com/google/security-research/pull/100#pullrequestreview-2085256469) apply.
> 
> Also added added additional comments.

Hello, @chanijindal1

I've updated exploit.md and exploit.c based on the comments.

Please check it.

Thanks.

2024-06-21 18:06 UTC, chanijindal1 commented
Thanks for the changes, looks good

2024-06-21 18:06 UTC, merged