Add kernelCTF CVE-2023-52447_cos
google/security-research pull request #105
Opened 2024-05-21 13:24 UTC by st424204

2024-08-21 09:21 UTC, JordyZomer requested changes
Hey! Thank you for your submission :)

I added some notes to the documentation that might make the write-up a bit more understandable for other people who'd be interested in reading it. Could you please address those? 

Thanks a lot! 😄

2024-08-21 09:21 UTC, JordyZomer commented on pocs/linux/kernelctf/CVE-2023-52447_cos/docs/exploit.md
> +With heap feng shui, the next chunk can be array_of_maps and we ovewrite its index 0 arraymap.
Could you explicitly detail the heap spraying or grooming techniques used to ensure the array_of_maps is allocated adjacent to the victim array_map?

2024-08-21 09:21 UTC, JordyZomer commented on pocs/linux/kernelctf/CVE-2023-52447_cos/docs/exploit.md
> +Another thread can free the arraymap and reclaim as array_of_maps.
Could you elaborate on how a different thread free's the arraymap and the details on how to reclaim it as an array_of_maps? The exploit mentions using another thread to free the array_map while the BPF program is running, but it doesn't elaborate on:
- Why multi-threading or forking is necessary for this exploit
- How the threads are synchronized (e.g., barriers, signals, etc.)
- What data is shared between the threads

2024-08-21 09:21 UTC, JordyZomer commented on pocs/linux/kernelctf/CVE-2023-52447_cos/docs/exploit.md
> +					     0x30, samplemap);
Can you explain why the value 0x30 is chosen here?

2024-08-21 09:21 UTC, JordyZomer commented on pocs/linux/kernelctf/CVE-2023-52447_cos/docs/exploit.md
> +		BPF_ST_MEM(BPF_W, BPF_REG_8, 4, 0x800), //modify map.max_entries
The new value written to map.max_entries is 0x800. Can you explain why this specific value is chosen, for example "we need this much room for the out-of-bounds because of X"?

2024-08-21 09:21 UTC, JordyZomer commented on pocs/linux/kernelctf/CVE-2023-52447_cos/docs/exploit.md
> +		BPF_ST_MEM(BPF_W, BPF_REG_8, 4,0xffff), //modify array->index_mask
The new value written to array->index_mask is 0xffff. Can you explain why it's useful  for enabling out-of-bounds access?

2024-08-21 09:21 UTC, JordyZomer commented on pocs/linux/kernelctf/CVE-2023-52447_cos/docs/exploit.md
> +The vulnerability is that bpf program can hold arraymap pointer without increase refcount if it's from array_of_maps.
Could you add the relevant code that's responsible for introducing the bug and explain why it allows you to get a reference to an arraymap without increasing it's refcount?

2024-08-21 09:21 UTC, JordyZomer commented on pocs/linux/kernelctf/CVE-2023-52447_cos/docs/exploit.md
> +It gives other thread chance to free that arraymap can reclaim it to another structure like array_of_maps.
Can you add some notes on which caches these objects are in?

2024-08-21 09:21 UTC, JordyZomer commented on pocs/linux/kernelctf/CVE-2023-52447_cos/docs/exploit.md
> +We can leak arrymap address and array_map_ops by malformed arraymap.
Could you add a note that based on array_map_ops you can find the kASLR base address?

2024-08-22 08:06 UTC, st424204 commented
Hey! Thanks for take a look into my submission.
I think the updated exploit.md has meet the requirement you mention in the threads

2024-09-26 09:11 UTC, JordyZomer commented
Thanks @st424204 ! Those changes make it way more clear :)

2024-09-26 09:11 UTC, merged

2025-04-09 03:02 UTC, seamaner commented
can this exploit work on lts?