Add kernelCTF CVE-2024-1085_cos
google/security-research pull request #108
Opened 2024-06-26 02:56 UTC by conlonialC

2024-07-26 09:59 UTC, koczkatamas requested changes
Hey!

I took a look at the exploit and I had to request a few changes (36 comments in total...) as I think some parts of the exploit could be explained better and there are some other code quality issues.

Please take a look and make the necessary changes.

Thanks!

2024-07-26 09:59 UTC, koczkatamas commented on pocs/linux/kernelctf/CVE-2024-1085_cos/exploit/cos-105-17412.226.43/exploit.c
> +    //while(1);
Remove this unused line.

2024-07-26 09:59 UTC, koczkatamas commented on pocs/linux/kernelctf/CVE-2024-1085_cos/exploit/cos-105-17412.226.43/exploit.c
> +    //(NFNL_SUBSYS_IPSET << 8) | (IPSET_CMD_CREATE);
What is this line about?

2024-07-26 09:59 UTC, koczkatamas commented on pocs/linux/kernelctf/CVE-2024-1085_cos/exploit/cos-105-17412.226.43/exploit.c
> +    char *key = malloc(0x40);
`key` and `key_end` variables are not used. Remove them.

2024-07-26 09:59 UTC, koczkatamas commented on pocs/linux/kernelctf/CVE-2024-1085_cos/exploit/cos-105-17412.226.43/exploit.c
> +    spray_tables(socket,0x100, pad, 0xd0);
Why are you spraying tables here? What heap layout are you trying to achieve here?

What kernel objects are part of the exploitation process (and created in the target slab `kmalloc-256`) and which objects are created by side-effect? E.g. are you only using `udata` for exploitation and `struct nft_table` and pipapo_set, etc are just side-effect?

Please also comment the answer into the source code and reference object by their exact name used in the kernel source code (e.g. `struct nft_table`).

2024-07-26 09:59 UTC, koczkatamas commented on pocs/linux/kernelctf/CVE-2024-1085_cos/exploit/cos-105-17412.226.43/exploit.c
> +    new_table(socket, table);
Comment here that this is "step 1" based on the writeup.

2024-07-26 09:59 UTC, koczkatamas commented on pocs/linux/kernelctf/CVE-2024-1085_cos/exploit/cos-105-17412.226.43/exploit.c
> +    struct nlmsghdr **msg_list = malloc(sizeof(struct nlmsghdr *)*5);
Comment here that this is "step 2" based on the writeup, also include that this part triggers the vulnerability itself.

2024-07-26 09:59 UTC, koczkatamas commented on pocs/linux/kernelctf/CVE-2024-1085_cos/exploit/cos-105-17412.226.43/exploit.c
> +    spray_tables(socket,0x100, pad, 0xd0);
Why did you choose `0xd0`? Were there any other consideration other than it will be allocated in `kmalloc-256`? Is there any header in the udata structure? If not then it means that `0x100` instead of `0xd0` would've worked as well?

2024-07-26 09:59 UTC, koczkatamas commented on pocs/linux/kernelctf/CVE-2024-1085_cos/exploit/cos-105-17412.226.43/exploit.c
> +    new_setelem(socket, table, pipapo_set, pad, 0xc0, target_obj, NULL, 0, NULL, 0, 1);
Same question as before: why `0xc0`? Why not `0xd0` (as before) or `0x100` (maximum size for `kmalloc-256`)?

2024-07-26 09:59 UTC, koczkatamas commented on pocs/linux/kernelctf/CVE-2024-1085_cos/exploit/cos-105-17412.226.43/exploit.c
> +    struct nl_sock * socket2 = nl_socket_alloc();
Why do you have to use a new socket? What would go wrong if you would just use `socket` instead of `socket2`?

2024-07-26 09:59 UTC, koczkatamas commented on pocs/linux/kernelctf/CVE-2024-1085_cos/exploit/cos-105-17412.226.43/exploit.c
> +    struct nl_sock * socket2 = nl_socket_alloc();
Comment here that this is "step 3" based on the writeup. Also include what does it do:

> Try to alloc the heap of the catchall set element `B` back by creating `nft_table` with `NFTA_TABLE_USERDATA`. Keep allocing heap, and each time you alloc a heap, check whether the heap has been alloced for(confirmed by whether the memory of the already created heap has been modified). After this step, We will find two `nft_table` with the same `udata`. We assume that the two `nft_tables` are `nft_table C` and `nft_table D`.

2024-07-26 09:59 UTC, koczkatamas commented on pocs/linux/kernelctf/CVE-2024-1085_cos/exploit/cos-105-17412.226.43/exploit.c
> +char *table_udata = NULL;
Explain in a comment what this variable is (it contains the table's udata after the `get_table` call I guess).

2024-07-26 09:59 UTC, koczkatamas commented on pocs/linux/kernelctf/CVE-2024-1085_cos/exploit/cos-105-17412.226.43/exploit.c
> +    //Now, we free many object to avoid crash
Can you explain what crash would happen without this step and why?

2024-07-26 09:59 UTC, koczkatamas commented on pocs/linux/kernelctf/CVE-2024-1085_cos/exploit/cos-105-17412.226.43/exploit.c
> +    for(i=0x80;i<0x180;i++){
Why are you removing objects between 0x80 ... 0x180? Because it is around your target object and you'd like to free everything around that object? Why? Won't it free the whole slab page?

2024-07-26 09:59 UTC, koczkatamas commented on pocs/linux/kernelctf/CVE-2024-1085_cos/exploit/cos-105-17412.226.43/exploit.c
> +    snprintf(tmp, 0x100, "table for test %d", a);
Comment here that this is "step 4" based on the writeup. Also include what does it do:
> Delete `nft_table C`.

2024-07-26 09:59 UTC, koczkatamas commented on pocs/linux/kernelctf/CVE-2024-1085_cos/exploit/cos-105-17412.226.43/exploit.c
> +    uint16_t bitmap_key = 0;
Comment here that this is "step 5 - 6" based on the writeup. Also include what does it do:
> Spray heap to get the heap of `nft_table C->udata` back. I spray heap by creating set element with `NFTA_SET_ELEM_EXPR` because I want to leak the `ops` pointer of the `nft_expr`. Then dump `nft_table D` (which points to the same memory area as where `nft_table C->udata` were and now it is sprayed with `nft_expr`). So now we can leak `nft_last_ops`.

2024-07-26 09:59 UTC, koczkatamas commented on pocs/linux/kernelctf/CVE-2024-1085_cos/exploit/cos-105-17412.226.43/exploit.c
> +    kernel_off = *(uint64_t *)(table_udata+0x28) - 0xFFFFFFFF828C9760;
What is `0xFFFFFFFF828C9760`? What did you leak here? `nft_last_ops`?

2024-07-26 09:59 UTC, koczkatamas commented on pocs/linux/kernelctf/CVE-2024-1085_cos/docs/exploit.md
> +- 6. Dump `nft_table D`. Now we leak `nft_last_ops`.
Mention that `nft_table D`'s udata contains the sprayed `nft_expr` object, so we can leak it's `ops` field which contains `nft_last_ops`.

2024-07-26 09:59 UTC, koczkatamas commented on pocs/linux/kernelctf/CVE-2024-1085_cos/exploit/cos-105-17412.226.43/exploit.c
> +    //now we get ops, we try to add a small setelem and leak it. We will use this setelem as expr->ops target.
Comment here that this is "step 7" based on the writeup. Also include what does it do:
> Create another set element `E`. Then dump the `nft_table D` again. We can get the `list_head.next` heap pointer of the set element `E` because each bitmap set element has a doubly linked list.
  ```c
  struct nft_bitmap_elem {
	struct list_head	head;
	struct nft_set_ext	ext;
  };
  ```

2024-07-26 09:59 UTC, koczkatamas commented on pocs/linux/kernelctf/CVE-2024-1085_cos/exploit/cos-105-17412.226.43/exploit.c
> +    //ops->dump
Explain that we are talking about `struct nft_expr_ops`'s `dump` field.

2024-07-26 09:59 UTC, koczkatamas commented on pocs/linux/kernelctf/CVE-2024-1085_cos/exploit/cos-105-17412.226.43/exploit.c
> +    //now we get ops, we try to add a small setelem and leak it. We will use this setelem as expr->ops target.
Why does this work? Is the `list_head.next` pointer contains the address of the object itself? So it linked list of 1 item?

2024-07-26 09:59 UTC, koczkatamas commented on pocs/linux/kernelctf/CVE-2024-1085_cos/exploit/cos-105-17412.226.43/exploit.c
> +    new_setelem(socket, table, bitmap_set, pad, 0x60, NULL, &bitmap_key, 2, NULL, 0, 0);
Why `0x60`? Explain the memory layout a bit better. `struct nft_bitmap_elem` is 32 bytes, it would not go into `kmalloc-256` just in itself, so I guess it is part of some other object?

2024-07-26 09:59 UTC, koczkatamas commented on pocs/linux/kernelctf/CVE-2024-1085_cos/exploit/cos-105-17412.226.43/exploit.c
> +    spray_tables(socket,0x400, pad, 0x80);
Why `0x80`? Is there a header on `udata` that it does not go into `kmalloc-128` instead of `kmalloc-256`?

2024-07-26 09:59 UTC, koczkatamas commented on pocs/linux/kernelctf/CVE-2024-1085_cos/exploit/cos-105-17412.226.43/exploit.c
> +    //build fake setelem
Which object are you building here exactly? Can you reference the exact struct name used on the kernel `struct nft_xxx`?

2024-07-26 09:59 UTC, koczkatamas commented on pocs/linux/kernelctf/CVE-2024-1085_cos/exploit/cos-105-17412.226.43/exploit.c
> +    //del table b first
Comment here that this is "step 9" based on the writeup. You can mention that `table b` is referenced in the writeup as `nft_table D` (or just use consistent naming between the code and writeup).

2024-07-26 09:59 UTC, koczkatamas commented on pocs/linux/kernelctf/CVE-2024-1085_cos/exploit/cos-105-17412.226.43/exploit.c
> +    	spray_tables(socket, 1, setelem_data, 0xd0);
Comment here that this is "step 10" based on the writeup. Also include what does it do:
> Fill the heap memory of `nft_table D ->udata` with fake `nft_expr` and ROP gadget.

2024-07-26 09:59 UTC, koczkatamas commented on pocs/linux/kernelctf/CVE-2024-1085_cos/exploit/cos-105-17412.226.43/exploit.c
> +        get_setelem(socket, table, bitmap_set, &bitmap_key, 2);
Comment here that this is "step 11" based on the writeup. Also include what does it do:
> Dump the set elements we create in step 5. Finally we will jmp to our ROP gadget.

2024-07-26 09:59 UTC, koczkatamas commented on pocs/linux/kernelctf/CVE-2024-1085_cos/exploit/cos-105-17412.226.43/exploit.c
> +    //Free the small setelem, and fill it with our target expr->ops->dump and expr->ops->type
Comment here that this is "step 8" based on the writeup. Also include what does it do:
> Delete set element `E`. Fill the heap memory of set element `E` through heap spraying.

2024-08-04 05:10 UTC, conlonialC commented
> Hey!
> 
> I took a look at the exploit and I had to request a few changes (36 comments in total...) as I think some parts of the exploit could be explained better and there are some other code quality issues.
> 
> Please take a look and make the necessary changes.
> 
> Thanks!

Hi,

I've updated the exploit.c to add all the changes. Please check it.

Thanks

2024-08-23 06:44 UTC, koczkatamas commented on pocs/linux/kernelctf/CVE-2024-1085_cos/exploit/cos-105-17412.226.43/exploit.c
> +    //now we get ops, we try to add a small setelem and leak it. We will use this setelem as expr->ops target.
Also mention what this step does. Now it's only "Step 7" is added.

2024-08-23 06:50 UTC, koczkatamas commented
Hey! There are still several unresolved comments (23 out of the original 36 comments). Could you please fix those too? Thanks!

2024-08-23 15:09 UTC, conlonialC commented on pocs/linux/kernelctf/CVE-2024-1085_cos/docs/exploit.md
> +Because the `setelem` object size we plan to use is between 0xc0-0x100, our target object cache is `kmalloc-256`
It's `struct nft_set_elem->priv` which is allocated in function `nft_set_elem_init`.
Yes, it's a dynamically sized object.
I've added it in exploit.md.

2024-08-23 15:18 UTC, conlonialC commented on pocs/linux/kernelctf/CVE-2024-1085_cos/docs/exploit.md
> +    msg_list[1] = del_table_msg(test_table);//kfree another heap to avoid crash
OK, I've updated the exploit.md.

2024-08-23 15:27 UTC, conlonialC commented on pocs/linux/kernelctf/CVE-2024-1085_cos/exploit/cos-105-17412.226.43/exploit.c
> +int table_num = 0;
OK, I've added it.

2024-08-23 15:28 UTC, conlonialC commented on pocs/linux/kernelctf/CVE-2024-1085_cos/exploit/cos-105-17412.226.43/exploit.c
> +    //(NFNL_SUBSYS_IPSET << 8) | (IPSET_CMD_CREATE);
Old code. I will delete it.

2024-08-23 15:40 UTC, conlonialC commented on pocs/linux/kernelctf/CVE-2024-1085_cos/exploit/cos-105-17412.226.43/exploit.c
> +    spray_tables(socket,0x100, pad, 0xd0);
Because the size of the target object(which will be freed twice) is between 0xc0-0x100. 
And there are no other considerration.
 There's no header in the udata because it's allocated by nla_memdup(Here is the code : https://elixir.bootlin.com/linux/v6.1.106/source/net/netfilter/nf_tables_api.c#L1400).
Yes.

2024-08-23 15:44 UTC, conlonialC commented on pocs/linux/kernelctf/CVE-2024-1085_cos/exploit/cos-105-17412.226.43/exploit.c
> +    new_setelem(socket, table, pipapo_set, pad, 0xc0, target_obj, NULL, 0, NULL, 0, 1);
This is because I want the size of the object created by nft_set_elem_init to be between 0xc0-0x100. Here 0xc0 is the size of NFT_SET_EXT_DATA in the nft_set_elem_init function.

2024-08-23 15:46 UTC, conlonialC commented on pocs/linux/kernelctf/CVE-2024-1085_cos/exploit/cos-105-17412.226.43/exploit.c
> +    struct nl_sock * socket2 = nl_socket_alloc();
Because some of my netfilter apis had some bugs, using `socket` seemed to have some unexpected IO problems, so I used the new `socket2` directly.

2024-08-23 16:07 UTC, conlonialC commented on pocs/linux/kernelctf/CVE-2024-1085_cos/exploit/cos-105-17412.226.43/exploit.c
> +    spray_tables(socket,0x400, pad, 0x80);
Because the size of the object(which is struct nft_set_elem -> priv) we free it step8  is between 0x80 - 0xc0. Here we want to fill the heap memory through heap spraying.

2024-08-23 16:42 UTC, conlonialC commented on pocs/linux/kernelctf/CVE-2024-1085_cos/exploit/cos-105-17412.226.43/exploit.c
> +    spray_tables(socket,0x100, pad, 0xd0);
Here I just want the target object (`struct nft_set_elem -> priv`, which will be released twice) and `table_obj_for_double_free_bypass` to be on the same page. Because during testing, only when they are on the same page (that is, the same slab), can the crash be effectively avoided.
Yes, I only used struct nft_table -> udata, struct nft_table is a side effect.
I've added a comment about function `spray_tables`:
/*
 Spray the heap through the udata of nft_table. In nftables, when creating a table, 
 you can let the kernel malloc and fill any size of heap memory by using NFTA_TABLE_USERDATA 
 (the corresponding code is in the function nf_tables_newtable). 
*/

2024-08-23 16:52 UTC, conlonialC commented on pocs/linux/kernelctf/CVE-2024-1085_cos/exploit/cos-105-17412.226.43/exploit.c
> +    //Now, we free many object to avoid crash
Because when we find two objects that are double freed, it also means that the next time the kernel heap of the same size is allocated, an illegal fd pointer is used, which will eventually lead to a crash.

2024-08-23 16:55 UTC, conlonialC commented on pocs/linux/kernelctf/CVE-2024-1085_cos/exploit/cos-105-17412.226.43/exploit.c
> +    for(i=0x80;i<0x180;i++){
As I mentioned above, when we find two objects that are double freed, it also means that the next time the kernel heap of the same size is allocated, an illegal fd pointer is used, which will eventually lead to a crash. The best way to avoid this is to release the object in the same slab as the target object.

2024-08-23 16:55 UTC, conlonialC commented on pocs/linux/kernelctf/CVE-2024-1085_cos/exploit/cos-105-17412.226.43/exploit.c
> +    //now we get ops, we try to add a small setelem and leak it. We will use this setelem as expr->ops target.
OK

2024-08-23 17:06 UTC, conlonialC commented on pocs/linux/kernelctf/CVE-2024-1085_cos/exploit/cos-105-17412.226.43/exploit.c
> +    new_setelem(socket, table, bitmap_set, pad, 0x60, NULL, &bitmap_key, 2, NULL, 0, 0);
The bitmap set elem created here is used as the target memory of expr[0]->ops in the subsequent hijacking of control flow. So its size does not need to meet 0xc0-0x100. (We only need to know its address, release it, and then use struct nft_table->udata to fill the content of expr[0]->ops we need)

2024-08-23 17:11 UTC, conlonialC commented on pocs/linux/kernelctf/CVE-2024-1085_cos/docs/exploit.md
> +- 1. Create a pipapo set `A`, and a catchall set element `B` in it.
Because the bitmap's setelement will have a doubly linked list pointer, we use the linked list pointer in step 7 to obtain a certain `struct nft_set_elem -> priv` pointer.

2024-08-23 17:16 UTC, conlonialC commented on pocs/linux/kernelctf/CVE-2024-1085_cos/exploit/cos-105-17412.226.43/exploit.c
> +    //now we get ops, we try to add a small setelem and leak it. We will use this setelem as expr->ops target.
the list_head.next pointer contains the address of the next object.  We get the freed object back by creating a set element in the bitmap set in step 5. And we create another set element of the bitmap set in step 7. After that, the list_head.next pointer of the set element we created in step5 will point to the set element we created in step7. So we get a pointer of the “struct nft_set_elem ->priv” which we created in step 7.

2024-08-23 17:27 UTC, conlonialC commented on pocs/linux/kernelctf/CVE-2024-1085_cos/exploit/cos-105-17412.226.43/exploit.c
> +    //build fake setelem
Here we are forging `struct nft_set_elem->priv`, and the forged data is filled in by `struct nft_table->udata`.

2024-08-23 17:34 UTC, conlonialC commented
> Hey! There are still several unresolved comments (23 out of the original 36 comments). Could you please fix those too? Thanks!

Hi, I've fixed all the comments, please check it! Thanks!

2024-09-23 11:07 UTC, merged