Add kernelCTF CVE-2023-4623_lts_cos
google/security-research pull request #110
Opened 2024-07-11 08:09 UTC by hexfoureight

2024-07-26 14:09 UTC, koczkatamas requested changes
Hey! Thank you for your submission!

I have four smaller change requests and/or questions (see them below), but otherwise it's a very high quality exploit and writeup, congrats!

2024-07-26 14:09 UTC, koczkatamas commented on pocs/linux/kernelctf/CVE-2023-4623_lts_cos/exploit/cos-97-16919.353.23/exploit.c
> +    init_rop(rop_buf + 4, jop_buf, kernel_base);
`+4` is because the `rtattr` is 4-bytes and we'd like to align our ROP chain into a 8-byte boundary (so start the ROP chain at offset 0x08)?

Maybe add a small comment about this.

2024-07-26 14:09 UTC, koczkatamas commented on pocs/linux/kernelctf/CVE-2023-4623_lts_cos/exploit/cos-97-16919.353.23/exploit.c
> +    netlink_write_noerr(nl_sock_fd, &new_qfq_qdisc);
Why is `netlink_write_noerr(nl_sock_fd, &new_qfq_qdisc);` called twice? Is it intentional or a mistake?

If it is intentional then what does the first call do and what does the second call?

2024-08-01 01:12 UTC, hexfoureight commented
Hi,

`netlink_write_noerr(nl_sock_fd, &new_qfq_qdisc)` is called twice intentionally. The first call creates the QFQ qdisc and the second call triggers ROP. I added a comment about this and the 4-byte offset.

I removed the unused gadget and some other unnecessary code. I also added a bit more detail on why the side-channel doesn't work on the github action instance.

2024-08-02 00:09 UTC, koczkatamas commented
> I removed the unused gadget and some other unnecessary code. I also added a bit more detail on why the side-channel doesn't work on the github action instance.

Thanks!

> `netlink_write_noerr(nl_sock_fd, &new_qfq_qdisc)` is called twice intentionally. The first call creates the QFQ qdisc and the second call triggers ROP. I added a comment about this and the 4-byte offset.

So I guess the first call detects in `tc_modify_qdisc` that this is a new Qdisc, so a new Qdisc is created, but does not trigger the modified `qfq_qdisc_ops.change` function pointer because it [jumps to the `create_n_graft` label](https://github.com/torvalds/linux/blob/c0ecd6388360d930440cc5554026818895199923/net/sched/sch_api.c#L1689) and [skipping the call to `qdisc_change`](https://github.com/torvalds/linux/blob/c0ecd6388360d930440cc5554026818895199923/net/sched/sch_api.c#L1747) which [would call `sch->ops->change`](https://github.com/torvalds/linux/blob/c0ecd6388360d930440cc5554026818895199923/net/sched/sch_api.c#L1417) (which is the overwritten function pointer). Do I understand correctly?

---

I also have a new question, which I don't understand fully, you mention that
> The new_qfq_qdisc message is constructed with two consecutive TCA_OPTIONS attributes

Why do you need two messages and separate the `jop_buf` and `rop_buf` messages (instead of just using one `rop_buf`)? Only the mentioned stack pivot (`push rsi ; jmp qword ptr [rsi - 0x70]`) could be found in the kernel binary, but there were no e.g. `push rsi ; jmp qword ptr [rsi]` or similar gadget in the kernel?

Btw you can send two TCA_OPTIONS because [the attribute parsing code](https://github.com/torvalds/linux/blob/c0ecd6388360d930440cc5554026818895199923/lib/nlattr.c#L643), simply does not check that you are using the same attribute multiple times, but only uses the latest one (which is just a pointer into the middle of user-supplied message structure)? That's kind of a bug in itself which at the end makes exploitation a bit easier, right?

2024-08-02 07:25 UTC, hexfoureight commented
> So I guess the first call detects in `tc_modify_qdisc` that this is a new Qdisc, so a new Qdisc is created, but does not trigger the modified `qfq_qdisc_ops.change` function pointer because it [jumps to the `create_n_graft` label](https://github.com/torvalds/linux/blob/c0ecd6388360d930440cc5554026818895199923/net/sched/sch_api.c#L1689) and [skipping the call to `qdisc_change`](https://github.com/torvalds/linux/blob/c0ecd6388360d930440cc5554026818895199923/net/sched/sch_api.c#L1747) which [would call `sch->ops->change`](https://github.com/torvalds/linux/blob/c0ecd6388360d930440cc5554026818895199923/net/sched/sch_api.c#L1417) (which is the overwritten function pointer). Do I understand correctly?

That's right.

> 
> I also have a new question, which I don't understand fully, you mention that
> 
> > The new_qfq_qdisc message is constructed with two consecutive TCA_OPTIONS attributes
> 
> Why do you need two messages and separate the `jop_buf` and `rop_buf` messages (instead of just using one `rop_buf`)? Only the mentioned stack pivot (`push rsi ; jmp qword ptr [rsi - 0x70]`) could be found in the kernel binary, but there were no e.g. `push rsi ; jmp qword ptr [rsi]` or similar gadget in the kernel?

It was just chosen to make the ROP chain slightly simpler, since alternative JOP gadgets like `push rsi ; jmp qword ptr [rsi + 0x2e]` would jump to an address in the middle of the ROP chain.

> Btw you can send two TCA_OPTIONS because [the attribute parsing code](https://github.com/torvalds/linux/blob/c0ecd6388360d930440cc5554026818895199923/lib/nlattr.c#L643), simply does not check that you are using the same attribute multiple times, but only uses the latest one (which is just a pointer into the middle of user-supplied message structure)? That's kind of a bug in itself which at the end makes exploitation a bit easier, right?

Yes. For the same effect the first `rtattr` could instead have an `rta_type` that is never checked for by the syscall.

2024-08-02 15:00 UTC, merged