Add kernelCTF CVE-2023-4147_mitigation
google/security-research pull request #111
Opened 2024-07-11 09:29 UTC by kevinrich1337

2024-09-11 15:07 UTC, artmetla commented on pocs/linux/kernelctf/CVE-2023-4147_mitigation/docs/exploit.md
> +- Create four chains, `Base`, `Vulnerable`, `Chain_Victim`, and `Target`. Set `NFT_CHAIN_BINDING` flag for `Vulnerable`.
Could you elaborate more please on why do we put those chains in different tables? Could we put them in one?

2024-09-19 13:57 UTC, artmetla commented on pocs/linux/kernelctf/CVE-2023-4147_mitigation/docs/exploit.md
> +- Delete the set element in `Victim`. This results in a UAF that references `Victim` that was freed in previous step [4].
Could you elaborate more on how does this happen? What is the call chain, which functions are involved on kernel level? Why is it important to have the operations in batch? 

Is this somewhat similar to https://github.com/oferchen/POC-CVE-2023-32233?

2024-09-24 14:27 UTC, artmetla requested changes

2024-09-24 14:27 UTC, artmetla commented on pocs/linux/kernelctf/CVE-2023-4147_mitigation/exploit/mitigation-6.1/exploit.c
> +        nftnl_rule_set_str(rules_victim2[i], NFTNL_RULE_CHAIN, chain_victim2_name);
How do we add rule to the chain with NFT_CHAIN_BINDING flag without using chain ID (like in vulnerability) or like in rule_lookup_set1 and chain2_name?

2024-09-29 09:12 UTC, kevinrich1337 commented on pocs/linux/kernelctf/CVE-2023-4147_mitigation/docs/exploit.md
> +- Create four chains, `Base`, `Vulnerable`, `Chain_Victim`, and `Target`. Set `NFT_CHAIN_BINDING` flag for `Vulnerable`.
There's no particular reason for using three different tables. We can put everything in table1 and it will work, we just need to change the rule_handle value in the exploit.c.

2024-09-29 09:12 UTC, kevinrich1337 commented on pocs/linux/kernelctf/CVE-2023-4147_mitigation/exploit/mitigation-6.1/exploit.c
> +        nftnl_rule_set_str(rules_victim2[i], NFTNL_RULE_CHAIN, chain_victim2_name);
We can add a rule to the chain with NFT_CHAIN_BINDING set before it is bound by an immediate expr.

2024-09-29 09:15 UTC, kevinrich1337 commented on pocs/linux/kernelctf/CVE-2023-4147_mitigation/docs/exploit.md
> +- Delete the set element in `Victim`. This results in a UAF that references `Victim` that was freed in previous step [4].
By deleting the lookup expr using vulnerability, we can make similar situation to CVE-2023-32233.

I added some details to the exploit.md.

2024-10-03 10:26 UTC, artmetla commented on pocs/linux/kernelctf/CVE-2023-4147_mitigation/exploit/mitigation-6.1/exploit.c
> +        nftnl_rule_set_str(rules_victim2[i], NFTNL_RULE_CHAIN, chain_victim2_name);
Ok. Does that means that on the lines 279 - 300: 

```
    struct nftnl_rule * rule_bind_chain_1_2 = nftnl_rule_alloc();

    nftnl_rule_set_str(rule_bind_chain_1_2, NFTNL_RULE_TABLE, table1_name);
    nftnl_rule_set_str(rule_bind_chain_1_2, NFTNL_RULE_CHAIN, chain1_name);

    struct nftnl_expr * expr_immediate = nftnl_expr_alloc("immediate");
    nftnl_expr_set_u32(expr_immediate, NFTNL_EXPR_IMM_DREG, NFT_REG_VERDICT);
    nftnl_expr_set_u32(expr_immediate, NFTNL_EXPR_IMM_VERDICT, NFT_GOTO);
    nftnl_expr_set_str(expr_immediate, NFTNL_EXPR_IMM_CHAIN, chain2_name);
    nftnl_rule_add_expr(rule_bind_chain_1_2, expr_immediate);

    struct nftnl_rule * rule_lookup_set1 = nftnl_rule_alloc();

    nftnl_rule_set_str(rule_lookup_set1, NFTNL_RULE_TABLE, table1_name);
    // nftnl_rule_set_str(rule_lookup_set1, NFTNL_RULE_CHAIN, chain2_name);
    nftnl_rule_set_u32(rule_lookup_set1, NFTNL_RULE_CHAIN_ID, chain_id);

    struct nftnl_expr * expr_lookup = nftnl_expr_alloc("lookup");
    nftnl_expr_set_u32(expr_lookup, NFTNL_EXPR_LOOKUP_SREG, NFT_REG32_00);
    nftnl_expr_set_str(expr_lookup, NFTNL_EXPR_LOOKUP_SET, set1_name);
    nftnl_expr_set_u32(expr_lookup, NFTNL_EXPR_LOOKUP_SET_ID, 1337);
    nftnl_rule_add_expr(rule_lookup_set1, expr_lookup);
```
and the lines 561 - 567: 
```
    nlh = nftnl_rule_nlmsg_build_hdr(mnl_nlmsg_batch_current(batch), NFT_MSG_NEWRULE, family, NLM_F_CREATE, seq++);
    nftnl_rule_nlmsg_build_payload(nlh, rule_bind_chain_1_2);
    mnl_nlmsg_batch_next(batch);

    nlh = nftnl_rule_nlmsg_build_hdr(mnl_nlmsg_batch_current(batch), NFT_MSG_NEWRULE, family, NLM_F_CREATE, seq++);
    nftnl_rule_nlmsg_build_payload(nlh, rule_lookup_set1);
    mnl_nlmsg_batch_next(batch);
```
we could change the logic of exploit to firstly add the `rule_lookup_set1` to `chain2_name` and then add the `expr_immediate` to actually bind the chain? I see that there is a commented line there which attempts to do same thing that I just described... If it's not possible could you explain why?

2024-10-03 10:28 UTC, artmetla commented on pocs/linux/kernelctf/CVE-2023-4147_mitigation/docs/exploit.md
> +- Create four chains, `Base`, `Vulnerable`, `Chain_Victim`, and `Target`. Set `NFT_CHAIN_BINDING` flag for `Vulnerable`.
Could you comment on this in PR#111 and PR112 please? This info could be added to exploit code itself or exploit.md.

2024-10-03 10:58 UTC, artmetla commented on pocs/linux/kernelctf/CVE-2023-4147_mitigation/docs/vulnerability.md
> +    - Capabilites: CAP_NET_ADMIN
I see that some of the comments from PR#112 could be applied to PR#111 as COS and Mitigation exploits are similar. For example here there is a small nit picking on Capabilites --> "Capabilities". Could you check recommendations on PR#112 and synchronise changes between PR#112 and PR111 please?

2024-10-03 13:37 UTC, artmetla commented on pocs/linux/kernelctf/CVE-2023-4147_mitigation/exploit/mitigation-6.1/exploit.c
> +    struct nftnl_set * set_delay_del =  nftnl_set_alloc();
Could you comment why do we need to have `set_delay_del` part here? In PR#112 COS exploit we don't do this operation.

2024-10-03 13:40 UTC, artmetla commented on pocs/linux/kernelctf/CVE-2023-4147_mitigation/exploit/mitigation-6.1/exploit.c
> +    expr_counter = nftnl_expr_alloc("counter");
In COS exploit PR#112 you rely on "last" expression. Is there a specific reason to use "counter" expression in mitigation exploit?

2024-10-03 13:48 UTC, artmetla commented on pocs/linux/kernelctf/CVE-2023-4147_mitigation/docs/exploit.md
> +- Delete the set element in `Victim`. This results in a UAF that references `Victim` that was freed in previous step [4].
Thanks. Sounds good

2024-11-07 11:18 UTC, kevinrich1337 commented on pocs/linux/kernelctf/CVE-2023-4147_mitigation/docs/exploit.md
> +- Create four chains, `Base`, `Vulnerable`, `Chain_Victim`, and `Target`. Set `NFT_CHAIN_BINDING` flag for `Vulnerable`.
I updated it to the exploit.c.

2024-11-07 11:19 UTC, kevinrich1337 commented on pocs/linux/kernelctf/CVE-2023-4147_mitigation/exploit/mitigation-6.1/exploit.c
> +    struct nftnl_set * set_delay_del =  nftnl_set_alloc();
I created the set_delay to create a delay between rule destroy and set element destroy to spray the set_rbtree. I added a comment to the exploit.c.

2024-11-07 11:19 UTC, kevinrich1337 commented on pocs/linux/kernelctf/CVE-2023-4147_mitigation/exploit/mitigation-6.1/exploit.c
> +    expr_counter = nftnl_expr_alloc("counter");
I used the different objects due to the different kernel versions of the COS (5.15) and mitigation (6.1) instances. I added a comment to the exploit.c.

2024-11-07 12:41 UTC, kevinrich1337 commented on pocs/linux/kernelctf/CVE-2023-4147_mitigation/exploit/mitigation-6.1/exploit.c
> +        nftnl_rule_set_str(rules_victim2[i], NFTNL_RULE_CHAIN, chain_victim2_name);
As you said, I think we can add a rule using the name by changing the order of the rules.

2024-11-08 15:06 UTC, artmetla commented on pocs/linux/kernelctf/CVE-2023-4147_mitigation/docs/exploit.md
> +- Create four chains, `Base`, `Vulnerable`, `Chain_Victim`, and `Target`. Set `NFT_CHAIN_BINDING` flag for `Vulnerable`.
Done

2024-11-08 15:06 UTC, artmetla commented on pocs/linux/kernelctf/CVE-2023-4147_mitigation/exploit/mitigation-6.1/exploit.c
> +    struct nftnl_set * set_delay_del =  nftnl_set_alloc();
Perfect. Thanks

2024-11-08 15:07 UTC, artmetla commented on pocs/linux/kernelctf/CVE-2023-4147_mitigation/exploit/mitigation-6.1/exploit.c
> +    expr_counter = nftnl_expr_alloc("counter");
Thanks for explanation

2024-12-20 19:09 UTC, artmetla approved these changes

2024-12-27 10:54 UTC, merged