Add kernelCTF CVE-2023-4147_lts_cos
google/security-research pull request #112
Opened 2024-07-11 09:46 UTC by kevinrich1337

2024-09-11 14:37 UTC, artmetla commented on pocs/linux/kernelctf/CVE-2023-4147_lts_cos/docs/exploit.md
> +- Create four chains, `Base`, `Vulnerable`, `Chain_Victim`, and `Target`. Set `NFT_CHAIN_BINDING` flag for `Vulnerable`.
Looks like in COS exploit those chains are placed in different tables (table1_name, table2_name, table3_name). Could you add more details on what is the reason to put them in different tables? LTS exploit puts everything into table1_name.

2024-09-11 14:46 UTC, artmetla commented on pocs/linux/kernelctf/CVE-2023-4147_lts_cos/docs/exploit.md
> +### Triggering Vulnerability
In mitigation version of exploit (https://github.com/google/security-research/pull/111/files?short_path=d6ecf7c) one could find steps to reproduce vulnerability. Could you add the instructions to reproduce the vulnerability in this PR too please?

2024-09-11 16:20 UTC, artmetla commented on pocs/linux/kernelctf/CVE-2023-4147_lts_cos/docs/exploit.md
> +- Trigger the vulnerability by replacing the rule in `Vulnerable`. This results in the `Victim` having a reference count of -1.
Could you specify which structure / field contains this reference counter?

2024-09-11 17:08 UTC, artmetla commented on pocs/linux/kernelctf/CVE-2023-4147_lts_cos/docs/exploit.md
> +- Create chains `Chain_Victim2_n`.
How many chains do we create? Could you explain why do we need that number of chains?

2024-09-11 17:10 UTC, artmetla commented on pocs/linux/kernelctf/CVE-2023-4147_lts_cos/docs/exploit.md
> +- Create rules `Rule_Victim2_n` in `Chain_Victim2_n`. The rules are allocated in `kmalloc-cg-192`.
Do I understand correctly that in exploit code (https://github.com/google/security-research/blob/35a16376bb92393d3268b45259ac67fb6b552cb1/pocs/linux/kernelctf/CVE-2023-4147_lts_cos/exploit/cos-105-17412.101.42/exploit.c#L255) set element spray goes before rules creation? Could you check that documented steps match the logic in code please?

2024-09-18 14:17 UTC, artmetla requested changes

2024-09-18 14:17 UTC, artmetla commented on pocs/linux/kernelctf/CVE-2023-4147_lts_cos/docs/exploit.md
> +- Delete the set element in `Set_Victim`. This results in a UAF that references `Set_Victim` that was freed in previous step.
Could you please elaborate why last 2 steps lead to UaF? Which functions in Linux kernel are called? Which reference counters are impacted (if any)? To which cache we're going to get pointer?

2024-09-24 14:32 UTC, artmetla requested changes

2024-09-24 14:32 UTC, artmetla commented on pocs/linux/kernelctf/CVE-2023-4147_lts_cos/exploit/cos-105-17412.101.42/exploit.c
> +        nftnl_chain_set_u32(chains_victim2[i], NFTNL_CHAIN_FLAGS, NFT_CHAIN_BINDING);
In LTS exploit we're replacing rules in chain with NFT_CHAIN_BINDING set, that triggers first reference counter decrease. 

Why can't we do the same in this exploit?
Could we take the same approach as in https://github.com/oferchen/POC-CVE-2023-32233 and skip creation bound chain? Could you elaborate why we can or can't please?

2024-09-29 08:34 UTC, kevinrich1337 commented on pocs/linux/kernelctf/CVE-2023-4147_lts_cos/docs/exploit.md
> +- Create four chains, `Base`, `Vulnerable`, `Chain_Victim`, and `Target`. Set `NFT_CHAIN_BINDING` flag for `Vulnerable`.
There's no particular reason for using three different tables. We can put everything in table1 and it will work, we just need to change the rule_handle value in the exploit.c.

2024-09-29 08:35 UTC, kevinrich1337 commented on pocs/linux/kernelctf/CVE-2023-4147_lts_cos/docs/exploit.md
> +The KASLR address is leaked through `chain->name`, which is stored in the verdict data of the immediate expr (`nft_immediate_expr.data.verdict`). The leak process is as follows:
Starting with commit [4bedf9ee] (https://git.kernel.org/pub/scm/linux/kernel/git/torvalds/linux.git/commit/?id=4bedf9eee016286c835e3d8fa981ddece5338795), it is possible to decrease the reference count of the victim chain in nft_immediate_deactivate because nft_rule_expr_deactivate is called in nft_immediate_deactivate. Therefore, the exploit in LTS kernel was possible using the method described above. However, in previous versions, nft_immediate_destroy calls nft_rule_expr_deactivate, so the exploit cannot be used in the same way as LTS kernel. Therefore, COS was exploited in a different way than LTS.

I added this explanation to the `exploit.md`.

2024-09-29 08:41 UTC, kevinrich1337 commented on pocs/linux/kernelctf/CVE-2023-4147_lts_cos/docs/exploit.md
> +- Create three chains, `Base`, `Vulnerable`, and `Victim`. Set `NFT_CHAIN_BINDING` flag for `Vulnerable`.
If a chain with the NFT_CHAIN_BINDING flag set is bound to an immediate expr, when this expr is destroyed, the bound chain and its rules will also be destroyed.

2024-09-29 08:42 UTC, kevinrich1337 commented on pocs/linux/kernelctf/CVE-2023-4147_lts_cos/docs/exploit.md
> +### Triggering Vulnerability
Yes, I added the reproduce step to the exploit.md.

2024-09-29 08:42 UTC, kevinrich1337 commented on pocs/linux/kernelctf/CVE-2023-4147_lts_cos/docs/exploit.md
> +- Trigger the vulnerability by replacing the rule in `Vulnerable`. This results in the `Victim` having a reference count of -1.
nft_chain->use contains the reference counter.

2024-09-29 08:42 UTC, kevinrich1337 commented on pocs/linux/kernelctf/CVE-2023-4147_lts_cos/docs/exploit.md
> +- Create chains `Chain_Victim2_n`.
I sprayed 0x30 chains. I believe this is a sufficient number for spray to succeed in the kernelCTF environment.

2024-09-29 08:43 UTC, kevinrich1337 commented on pocs/linux/kernelctf/CVE-2023-4147_lts_cos/docs/exploit.md
> +- Create rules `Rule_Victim2_n` in `Chain_Victim2_n`. The rules are allocated in `kmalloc-cg-192`.
In line 255, it prepares the necessary objects for the exploit. The actual spray of set element in the exploit is performed on line 897.

2024-09-29 08:46 UTC, kevinrich1337 commented on pocs/linux/kernelctf/CVE-2023-4147_lts_cos/docs/exploit.md
> +- Trigger the vulnerability by replacing the rule in `Vulnerable`. This results in the `Victim` having a reference count of -1.
- Replacing the rule in Vulnerable chain will delete the old rule in the Vulnerable. So, the reference counter of Victim is decreased.
- Then, we delete the rule R1 to decrease the reference counter of Victim again.

I updated the missed explanations in the writeup.md.

2024-09-29 08:49 UTC, kevinrich1337 commented on pocs/linux/kernelctf/CVE-2023-4147_lts_cos/docs/exploit.md
> +- Delete the set element in `Set_Victim`. This results in a UAF that references `Set_Victim` that was freed in previous step.
I updated the exploit.md as follows. I hope this answers your questions.

- Delete the `R1`. When `R1` is destroyed, `nft_immediate_destroy` is called to destroy `R2`, the rule of `Vulnerable` that is bound to `R1`. This results in `Set_Victim` being free in `nft_lookup_destroy` from the destroy phase.
- Delete the set element in `Set_Victim`. This will reference the `Set_Victim` freed in the previous step in the `nf_tables_set_elem_destroy`, causing a UAF.
...
- Spray fake rules using `nft_table->udata` into freed `Rule_Victim2_n` (`kmalloc-cg-192`). Set `nft_rule->udata` of the fake rule to 1 and `nft_rule->udata->len` to 0xff.
- Get the fake rule will read 0xff bytes start from `nft_rule->udata`. As a result, we can obtain kbase (`nft_last_ops`) and heap address (`nft_rule.list.next` and `nft_rule.list.prev`) of `Rule_Targret_n`.

2024-09-29 08:52 UTC, kevinrich1337 commented on pocs/linux/kernelctf/CVE-2023-4147_lts_cos/exploit/cos-105-17412.101.42/exploit.c
> +        nftnl_chain_set_u32(chains_victim2[i], NFTNL_CHAIN_FLAGS, NFT_CHAIN_BINDING);
Since this vulnerability is related to chain binding, creating bound chain is required. It is also possible to exploit the vulnerability in LTS similar to https://github.com/oferchen/POC-CVE-2023-32233 that leverages freed set element. I think the exploit method in the COS kernel is somewhat similar to https://github.com/oferchen/POC-CVE-2023-32233.

2024-09-29 08:56 UTC, kevinrich1337 commented
Hello, @artmetla. 

I updated the write-up based on your review.

Please check it.

Thanks.

2024-10-01 14:53 UTC, artmetla commented on pocs/linux/kernelctf/CVE-2023-4147_lts_cos/docs/exploit.md
> +- Trigger the vulnerability by replacing the rule in `Vulnerable`. This results in the `Victim` having a reference count of -1.
Please add this information to exploit.md file. Could be something like `reference count (nft_chain->use ) of -1`.

2024-10-01 14:56 UTC, artmetla commented on pocs/linux/kernelctf/CVE-2023-4147_lts_cos/docs/exploit.md
> +- Create chains `Chain_Victim2_n`.
Sounds good. Could you change exploit.md then to include this number and mention that `Chain_Victim2_n` are sprayed, basically 0x30 chains created? Could you also add a word or two why this spray is needed (maybe some next step could be refered)?

2024-10-01 14:58 UTC, artmetla commented on pocs/linux/kernelctf/CVE-2023-4147_lts_cos/docs/exploit.md
> +- Create three chains, `Base`, `Vulnerable`, and `Victim`. Set `NFT_CHAIN_BINDING` flag for `Vulnerable`.
Sounds clear. Thanks for adding it to `Triggering Vulnerability` section.

2024-10-02 10:46 UTC, artmetla commented on pocs/linux/kernelctf/CVE-2023-4147_lts_cos/docs/exploit.md
> +- Create four chains, `Base`, `Vulnerable`, `Chain_Victim`, and `Target`. Set `NFT_CHAIN_BINDING` flag for `Vulnerable`.
Could you add comment about this to the exploit code (exploit.c file)?

2024-10-02 12:00 UTC, artmetla commented on pocs/linux/kernelctf/CVE-2023-4147_lts_cos/docs/exploit.md
> +- Trigger the vulnerability by replacing the rule in `Vulnerable`. This results in the `Victim` having a reference count of -1.
Thanks for an update. Sounds clear!

2024-10-02 12:45 UTC, artmetla commented on pocs/linux/kernelctf/CVE-2023-4147_lts_cos/docs/exploit.md
> +- Spray rhash sets `Set_Spray_n`. When destroying an `nf_tables_set_elem_destroy` element, `nft_set_ext` is used [10], and `nft_set_ext` is retrieved by referencing `set->ops->elemsize` [12]. Thus, a
Could you also elaborate why we need to create [set_delay](https://github.com/google/security-research/blob/35a16376bb92393d3268b45259ac67fb6b552cb1/pocs/linux/kernelctf/CVE-2023-4147_lts_cos/exploit/cos-105-17412.101.42/exploit.c#L372)? 

Could you also explain why do we need to delete this set after triggering:
```
    nlh = nftnl_rule_nlmsg_build_hdr(mnl_nlmsg_batch_current(batch), NFT_MSG_DELRULE, family, 0, seq++);
    nftnl_rule_nlmsg_build_payload(nlh, rule_bind_chain_1_2_del);
    mnl_nlmsg_batch_next(batch);
```
before running deletion of set element in anonymous set:
```
    nlh = nftnl_set_nlmsg_build_hdr(mnl_nlmsg_batch_current(batch), NFT_MSG_DELSETELEM, family, 0, seq++);
    nftnl_set_elems_nlmsg_build_payload(nlh, set1_elem);
    mnl_nlmsg_batch_next(batch);
```
?

2024-10-02 15:37 UTC, artmetla commented on pocs/linux/kernelctf/CVE-2023-4147_lts_cos/docs/exploit.md
> +- Spray rhash sets `Set_Spray_n`. When destroying an `nf_tables_set_elem_destroy` element, `nft_set_ext` is used [10], and `nft_set_ext` is retrieved by referencing `set->ops->elemsize` [12]. Thus, a
```suggestion
- Spray rhash sets `Set_Spray_n`. When destroying an `nf_tables_set_elem_destroy` element, `nft_set_ext` is used [10], and `nft_set_ext` is retrieved by referencing `set->ops->elemsize` [12]. Thus, a rhash set with `elemsize` of 8 is overwritten by an rbtree set with `elemsize` of 24, causing the `nft_set_elem_expr_destroy` to reference the wrong `nft_set_ext`. We manipulate the offset to destroy the `immedieate expr` in `Rule_Victim_n`, that is allocated after the element, in [11]. This frees `Rule_Victim2_n` of `Chain_Victim2_n` in the `nft_immediate_destroy`. However, `Chain_Victim2_n` and `Rule_Victim2_n` remain accessible.
```

2024-10-03 10:43 UTC, artmetla commented on pocs/linux/kernelctf/CVE-2023-4147_lts_cos/docs/exploit.md
> +- Create rules `Rule_Victim2_n` in `Chain_Victim2_n`. The rules are allocated in `kmalloc-cg-192`.
Sounds clear. Thanks

2024-10-03 13:44 UTC, artmetla commented on pocs/linux/kernelctf/CVE-2023-4147_lts_cos/exploit/cos-105-17412.101.42/exploit.c
> +        expr_last = nftnl_expr_alloc("last");
Looks like in Mitigation exploit PR#111 you skip creation of this expressions. Why do we need those in COS exploit? Could you comment in the code of exploit?

2024-10-03 13:46 UTC, artmetla commented on pocs/linux/kernelctf/CVE-2023-4147_lts_cos/docs/exploit.md
> +- Delete the set element in `Set_Victim`. This results in a UAF that references `Set_Victim` that was freed in previous step.
Thank you very much for those extra details!

2024-10-03 14:08 UTC, artmetla commented on pocs/linux/kernelctf/CVE-2023-4147_lts_cos/exploit/lts-6.1.36/exploit.c
> +    nftnl_rule_set_u32(rule_replace_3, NFTNL_RULE_CHAIN_ID, 1337);
We're doing rule replace in this exploit by ID, as this chain is already bound by `rule_bind_chain_1_2`. Following our conversation in PR#111. Could we change the logic of exploit, to firstly create `rule_bind_chain_2_3` then call replacement with `rule_dangling_3` and then trigger deletion of `rule_bind_chain_1_2`? If so, we would not need to add the `rule_dangling_3` to the chain by ID?

2024-10-03 14:09 UTC, artmetla commented on pocs/linux/kernelctf/CVE-2023-4147_lts_cos/exploit/cos-105-17412.101.42/exploit.c
> +        nftnl_chain_set_u32(chains_victim2[i], NFTNL_CHAIN_FLAGS, NFT_CHAIN_BINDING);
Sounds clear. Thanks

2024-10-19 14:51 UTC, kevinrich1337 commented on pocs/linux/kernelctf/CVE-2023-4147_lts_cos/docs/exploit.md
> +- Create four chains, `Base`, `Vulnerable`, `Chain_Victim`, and `Target`. Set `NFT_CHAIN_BINDING` flag for `Vulnerable`.
I updated it to the exploit.c

2024-10-19 14:51 UTC, kevinrich1337 commented on pocs/linux/kernelctf/CVE-2023-4147_lts_cos/docs/exploit.md
> +- Create chains `Chain_Victim2_n`.
I updated it to the exploit.md

2024-10-19 14:52 UTC, kevinrich1337 commented on pocs/linux/kernelctf/CVE-2023-4147_lts_cos/docs/exploit.md
> +- Spray rhash sets `Set_Spray_n`. When destroying an `nf_tables_set_elem_destroy` element, `nft_set_ext` is used [10], and `nft_set_ext` is retrieved by referencing `set->ops->elemsize` [12]. Thus, a
I created the set_delay to create a delay between rule destroy and set element destroy to spray the set_rbtree. I added a comment to the exploit.c.

2024-10-19 14:54 UTC, kevinrich1337 commented on pocs/linux/kernelctf/CVE-2023-4147_lts_cos/exploit/lts-6.1.36/exploit.c
> +    nftnl_rule_set_u32(rule_replace_3, NFTNL_RULE_CHAIN_ID, 1337);
We can create rule_bind_chain_1_2 later to bound the chain2 late, so we can replace rule_bind_chain_2_3 without using the chain ID. I think this is a missed point in CVE-2023-4147 and CVE-2023-5197  handles it by preventing replacing on chains with the bound flag present.

2024-10-19 14:56 UTC, kevinrich1337 commented on pocs/linux/kernelctf/CVE-2023-4147_lts_cos/exploit/cos-105-17412.101.42/exploit.c
> +        expr_last = nftnl_expr_alloc("last");
I used the different objects due to the different kernel versions of the COS (5.15) and mitigation (6.1) instances.

2024-10-21 10:39 UTC, artmetla commented on pocs/linux/kernelctf/CVE-2023-4147_lts_cos/docs/exploit.md
> +- Create four chains, `Base`, `Vulnerable`, `Chain_Victim`, and `Target`. Set `NFT_CHAIN_BINDING` flag for `Vulnerable`.
Perfect. Thanks

2024-10-21 10:39 UTC, artmetla commented on pocs/linux/kernelctf/CVE-2023-4147_lts_cos/docs/exploit.md
> +- Trigger the vulnerability by replacing the rule in `Vulnerable`. This results in the `Victim` having a reference count of -1.
Perfect. Thanks

2024-10-21 10:50 UTC, artmetla commented on pocs/linux/kernelctf/CVE-2023-4147_lts_cos/docs/exploit.md
> +- Create chains `Chain_Victim2_n`.
Thanks

2024-10-21 10:52 UTC, artmetla commented on pocs/linux/kernelctf/CVE-2023-4147_lts_cos/exploit/cos-105-17412.101.42/exploit.c
> +        expr_last = nftnl_expr_alloc("last");
Sounds good. Could you mention this in code comment in `exploit.c` please?

2024-11-07 11:18 UTC, kevinrich1337 commented on pocs/linux/kernelctf/CVE-2023-4147_lts_cos/exploit/cos-105-17412.101.42/exploit.c
> +        expr_last = nftnl_expr_alloc("last");
Yes, I added the comment in the exploit.c

2024-11-08 15:05 UTC, artmetla commented on pocs/linux/kernelctf/CVE-2023-4147_lts_cos/exploit/cos-105-17412.101.42/exploit.c
> +        expr_last = nftnl_expr_alloc("last");
Done

2024-12-20 19:08 UTC, artmetla approved these changes

2024-12-27 10:53 UTC, merged