Add kernelCTF CVE-2024-26808_cos
google/security-research pull request #113
Opened 2024-07-19 07:23 UTC by st424204

2024-08-23 08:30 UTC, koczkatamas requested changes
Hey!

Thank you for the submission!

I've requested a few changes below. There are 11 comments, the Github UI will only slow 10 by default and will hide 1 additional comment, please make sure to click on the "Load more..." button to see all comments.

Thanks!

2024-08-23 08:30 UTC, koczkatamas commented on pocs/linux/kernelctf/CVE-2024-26808_cos/docs/exploit.md
> +8. Reclaim it as another `pipe_buffer` B.
Remove this step if not needed (from the documentation and from the exploit).

2024-08-23 08:30 UTC, koczkatamas commented on pocs/linux/kernelctf/CVE-2024-26808_cos/docs/exploit.md
> +9. Free pipe_buffer B and reclaim it as `msg_msgseg`.
Mention that you are using `msg_msgseg` because you a structure which cannot be easily corrupted by the `pipe_buffer` which will take its place (you can also mention that you cannot use the previous `msg_msg` you used before, because `pipe_buffer` would overwrite its important fields and it would crash).

2024-08-26 07:33 UTC, st424204 commented on pocs/linux/kernelctf/CVE-2024-26808_cos/exploit/cos-105-17412.294.36/exploit.c
> +	mnl_attr_put_str(nlh, IFLA_INFO_KIND, "dummy");
We create dummy network interfaces to reach vulnerable code path without affect other devices. (We just followed the example in rtnl source code). CONFIG_DUMMY is enabled by default in most of linux distro, it will register "dummy" kind at function dummy_init_module, please refer to drivers\net\dummy.c

2024-08-26 08:55 UTC, d4em0n commented on pocs/linux/kernelctf/CVE-2024-26808_cos/docs/exploit.md
> +13. Free this `msg_msgseg`/`pipe_buffer` A and overwrite again with new content.
fixed

2024-08-26 08:55 UTC, d4em0n commented on pocs/linux/kernelctf/CVE-2024-26808_cos/docs/exploit.md
> +4. We fill `msg_msg.next` (first 8 byte offset) with kmalloc-cg-192 by send `msg_msg` with size 0x90 for every `msg_msg` that already placed in kmalloc-cg-4k.
I add this in the step: `kmalloc-cg-192 guarantee that the first byte doesn't contain null byte, so we can leak kmalloc-cg-192 msg_msg addr using UAF leak.`

2024-08-26 08:55 UTC, d4em0n commented on pocs/linux/kernelctf/CVE-2024-26808_cos/docs/exploit.md
> +9. Free pipe_buffer B and reclaim it as `msg_msgseg`.
fixed

2024-08-26 08:57 UTC, d4em0n commented on pocs/linux/kernelctf/CVE-2024-26808_cos/docs/exploit.md
> +2. `packet_fanout` object has `net` address in the first 8 byte, we leak this using UAF leak primitive.
I add in step 2: `we leak net using UAF leak primitive to satisfy condition dev_net(dev) != net when perform arbitrary free at step 6.`. the first 8 bytes leak already explained at UAF Leak section

2024-08-26 09:16 UTC, st424204 commented on pocs/linux/kernelctf/CVE-2024-26808_cos/exploit/cos-105-17412.294.36/exploit.c
> +	struct fanout_args fa = {.max_num_members = 0x100};
max_num_members == 0x1000 to make struct packet_fanout in kmalloc-4096 cache
```c
match = kvzalloc(struct_size(match, arr, args->max_num_members),
				 GFP_KERNEL);
```
```
gef➤  p sizeof(struct packet_fanout) + sizeof(struct sock*)*0x100
$4 = 0x8c0
```

2024-08-26 09:16 UTC, st424204 commented on pocs/linux/kernelctf/CVE-2024-26808_cos/exploit/cos-105-17412.294.36/exploit.c
> +			p->offset = 0x7a0 - 1;
fixed

2024-08-26 09:16 UTC, st424204 commented on pocs/linux/kernelctf/CVE-2024-26808_cos/docs/exploit.md
> +8. Reclaim it as another `pipe_buffer` B.
fixed

2024-08-26 09:20 UTC, st424204 commented on pocs/linux/kernelctf/CVE-2024-26808_cos/docs/exploit.md
> +11. Read from `msg_msgseg` to read content of `pipe_buffer` A.
fixed

2024-08-26 09:20 UTC, st424204 commented on pocs/linux/kernelctf/CVE-2024-26808_cos/exploit/cos-105-17412.294.36/exploit.c
> +			p->page += (0x863000 >> 6);
fixed

2024-09-23 12:23 UTC, merged

2024-09-23 12:23 UTC, koczkatamas commented
Thank you for the fixes! Merged the PR!