Add kernelCTF CVE-2024-41009_lts_cos
google/security-research pull request #118
Opened 2024-07-23 08:27 UTC by st424204

2024-12-05 15:29 UTC, JordyZomer requested changes
Thanks for the PR! I've written down a few comments, could you modify those (also for both exploits)? Other than that, looks good to me :)

2024-12-05 15:29 UTC, JordyZomer commented on pocs/linux/kernelctf/CVE-2024-41009_lts_cos/exploit/cos-105-17412.370.23/exploit.c
> +#define BPF_HEAVY_JOB                             \
This isn't used right? Could you remove the parts that are unused so that it's clearer for other readers? :)

2024-12-05 15:29 UTC, JordyZomer commented on pocs/linux/kernelctf/CVE-2024-41009_lts_cos/docs/exploit.md
> +We modify `pg_off` of chunk A to `2`, so the meta pages that calculated with `bpf_ringbuf_restore_from_rec` will point to our controlled content at mmap-ed consumer pos data.
Can you add why changing this to 2 will point to the mmaped data?

2024-12-06 07:10 UTC, d4em0n commented
Thanks for the review @JordyZomer.
We fixed all of them and add more clearer statements as well.
Please check it again, thanks!

2024-12-06 10:41 UTC, merged

2024-12-06 10:41 UTC, JordyZomer commented
Thanks for the changes @d4em0n !