Add kernelCTF CVE-2024-26642_cos
google/security-research pull request #130
Opened 2024-09-03 02:38 UTC by lonialcon2

2025-03-14 13:11 UTC, koczkatamas requested changes
Hey,

This is just a quick code quality review. We're planning to review the submissions more deeply (actually understanding what the exploit does) in two weeks.

Please read our new (although still draft) [style guide](https://google.github.io/security-research/kernelctf/style_guide) and refactor your exploit to follow the recommendations there.

I've also left some explicit comments. Please fix the similar issues in your other PRs as well (in addition to the comments in those PRs).

There are 30 comments in this review. If you don't see them all (only the first 10), make sure you are expanding the comment list in the Github UI (there is a "20 hidden conversations" button in the middle of the comments).

Thanks for the submission and PR!

2025-03-14 13:11 UTC, koczkatamas commented on pocs/linux/kernelctf/CVE-2024-26642_cos/exploit/cos-105-17412.294.23/exploit.c
> +void primitive_0(struct nl_sock *socket, char *table, char *target_obj, int repeat_time){
Comments are explaining what the `primitive_0` does, but also consider choosing a descriptive function name as well, e.g. `primitive_decrease_nft_object_use`.

2025-03-14 13:11 UTC, koczkatamas commented on pocs/linux/kernelctf/CVE-2024-26642_cos/exploit/cos-105-17412.294.23/exploit.c
> +void primitive_1(struct nl_sock *socket, char *table, char *target_chain, int repeat_time){
Comments are explaining what the `primitive_1` does, but also consider choosing a descriptive function name as well, e.g. `primitive_decrease_nft_chain_use`.

2025-03-14 13:11 UTC, koczkatamas commented on pocs/linux/kernelctf/CVE-2024-26642_cos/exploit/cos-105-17412.294.23/exploit.c
> +    *(uint64_t *)&ops[0x40] = kernel_off + 0xFFFFFFFF81519693;//leave ; ret
Consider using `#define`s instead of adding addresses directly. Please take a look at [our style guide](https://google.github.io/security-research/kernelctf/style_guide#rop-chains) about the expected format.

2025-03-14 13:11 UTC, koczkatamas commented on pocs/linux/kernelctf/CVE-2024-26642_cos/exploit/cos-105-17412.294.23/exploit.c
> +    *(uint64_t *)&ops[0x70] = kernel_off + 0xFFFFFFFF8371BF00;//last type
What is the exact kernel symbol of `last type`?

2025-03-14 13:11 UTC, koczkatamas commented on pocs/linux/kernelctf/CVE-2024-26642_cos/exploit/cos-105-17412.294.23/exploit.c
> +    kernel_off = leak_ops - 0xFFFFFFFF82ACB840;
Define what's `0xFFFFFFFF82ACB840` exactly (which kernel symbol).

2025-03-14 13:11 UTC, koczkatamas commented on pocs/linux/kernelctf/CVE-2024-26642_cos/exploit/cos-105-17412.294.23/exploit.c
> +    uint64_t obj_a = *(uint64_t *)&leak_data[0xcb];
Comment here what is leaked here exactly (what is the value of `obj_a` and `obj_b`). Which fields of which object is at `0xcb` and `0xcb+8`?

2025-03-14 13:11 UTC, koczkatamas commented on pocs/linux/kernelctf/CVE-2024-26642_cos/exploit/cos-105-17412.294.23/exploit.c
> +    *(uint64_t *)&ops[0xc8] = user_rsp|8;
Comment here why do you need the `|8` here?

2025-03-14 13:11 UTC, koczkatamas commented on pocs/linux/kernelctf/CVE-2024-26642_cos/exploit/cos-105-17412.294.23/exploit.c
> +    char *key = malloc(0x40);
Comment here why you choose the sizes of `0x40`, `48` and `0x100`. Does it matter from the exploitation point-of-view? E.g. to which cache get into?

2025-03-25 05:16 UTC, chanijindal1 reviewed
Hi! Thanks again for the submission and pull request. Main thing that I'd like to see improved is a bit more clarity on the constants. Either making named constants or commenting them when it's not clear.

2025-03-29 15:58 UTC, lonialcon2 commented on pocs/linux/kernelctf/CVE-2024-26642_cos/exploit/cos-105-17412.294.23/exploit.c
> +int nl_callback_leak_ops(struct nl_msg* recv_msg, void* arg)
No. No need to check here.

2025-03-29 16:03 UTC, lonialcon2 commented on pocs/linux/kernelctf/CVE-2024-26642_cos/exploit/cos-105-17412.294.23/exploit.c
> +    //step 6 jmp to ROP;
In step 6, we change the `size` of `NFT_SET_EXT_EXPRESSIONS`. This means we can construct some fake exprs. By controlling fake expr->ops, we can hijack the control flow.

2025-03-29 16:04 UTC, lonialcon2 commented
> Hi! Thanks again for the submission and pull request. Main thing that I'd like to see improved is a bit more clarity on the constants. Either making named constants or commenting them when it's not clear.

Hi, I have modified it according to your comments. Please check it. Thanks.

2025-04-07 08:37 UTC, merged