Add kernelCTF CVE-2024-26642_mitigation
google/security-research pull request #131
Opened 2024-09-03 06:51 UTC by conlonial

2025-03-14 13:15 UTC, koczkatamas requested changes
Hey,

This is just a quick code quality review. We're planning to review the submissions more deeply (actually understanding what the exploit does) in two weeks.

Please read our new (although still draft) [style guide](https://google.github.io/security-research/kernelctf/style_guide) and refactor your exploit to follow the recommendations there.

I've also left some explicit comments. Please fix the similar issues in your other PRs as well (in addition to the comments in those PRs) and also fix similar issue found in other PRs here.

Thanks for the submission and PR!

2025-03-14 13:15 UTC, koczkatamas commented on pocs/linux/kernelctf/CVE-2024-26642_mitigation/exploit/mitigation-v3-6.1.55/poc.h
> +  #if 0
Please remove commented out code: https://google.github.io/security-research/kernelctf/style_guide#commented-out-code

2025-03-14 13:15 UTC, koczkatamas commented on pocs/linux/kernelctf/CVE-2024-26642_mitigation/exploit/mitigation-v3-6.1.55/poc.h
> +#define MY_TABLE "foo_tab", strlen("foo_tab")
Please remove unused code: https://google.github.io/security-research/kernelctf/style_guide#unused-code

2025-03-14 13:15 UTC, koczkatamas commented on pocs/linux/kernelctf/CVE-2024-26642_mitigation/exploit/mitigation-v3-6.1.55/poc.h
> +#define FOR_ALL_OFFSETS(x) do { \
This logic seems to be overly complicated. We prefer this format better: https://google.github.io/security-research/kernelctf/style_guide#rop-chains

2025-03-14 13:15 UTC, koczkatamas commented on pocs/linux/kernelctf/CVE-2024-26642_mitigation/exploit/mitigation-v3-6.1.55/poc.h
> +    #define x(name) { name -= diff; printf("corrected %s to %llx\n", #name, name); }
This logic seems to be overly complicated. We prefer this format better: https://google.github.io/security-research/kernelctf/style_guide#rop-chains

2025-03-26 01:12 UTC, chanijindal1 requested changes
Thanks for the submission and pull request. Just a couple things that I thought could be improved to make it clearer.

2025-03-29 00:27 UTC, conlonial commented on pocs/linux/kernelctf/CVE-2024-26642_mitigation/exploit/mitigation-v3-6.1.55/exploit.c
> +    printf("spraying payloads ..\n");
No, the function spray_payload is trying to fill the free'd struct nft_rule_blob. As I wrote in exploit.md, you can read this part: https://github.com/google/security-research/blob/master/pocs/linux/kernelctf/CVE-2023-6817_mitigation/docs/exploit.md#heap-spray

2025-03-29 16:20 UTC, conlonial commented on pocs/linux/kernelctf/CVE-2024-26642_mitigation/exploit/mitigation-v3-6.1.55/exploit.c
> +void primitive_decrease_nft_chain_use(struct nl_sock *socket, char *table, char *target_chain){
OK, I understand it.

2025-03-29 16:20 UTC, conlonial commented
> Thanks for the submission and pull request. Just a couple things that I thought could be improved to make it clearer.

Hi, I have modified it according to your comments. Please check it. Thanks.

2025-04-07 08:51 UTC, merged