Add kernelCTF CVE-2023-6931_lts_cos
google/security-research pull request #135
Opened 2024-10-16 16:53 UTC by hexfoureight

2025-03-14 13:26 UTC, koczkatamas requested changes
Hey,

This is just a quick code quality review. We're planning to review the submissions more deeply (actually understanding what the exploit does) in two weeks.

In general, the code quality looks great, some of the calculations are hard to understand but I think they are explained well enough in the writeup. I've left two comments about improvement ideas.

We also have a draft style guide now: https://google.github.io/security-research/kernelctf/style_guide. Although your exploit code is usually already high quality,  so you probably don't have to depend on it too much, but let us know if you have any feedback regarding the style guide.

Thanks for the submission and PR!

2025-03-14 13:26 UTC, koczkatamas commented on pocs/linux/kernelctf/CVE-2023-6931_lts_cos/exploit/lts-6.1.61/exploit.c
> +#define NUM_INCS1 0x830
If possible, then I think it would make it clearer what's going on if you would `#define` the kernel address for `sk_destruct` and `sk_write_space` and then use `#define NUM_INCS1 (SK_DESTRUCT - SK_WRITE_SPACE)`, maybe with a static assert that `NUM_INCS1 > 0`.

Similarly for `NUM_INCS2` you can add `#define`s for `netlink_bind` and `netlink_bind_ret_addr`.

This helps porting the exploit from one target to another.

2025-03-14 13:26 UTC, koczkatamas commented on pocs/linux/kernelctf/CVE-2023-6931_lts_cos/exploit/lts-6.1.61/exploit.c
> +    rop++;
This `rop++` is still part fo the stack pivot based of `pop rbp` and not related to `commit_creds`, right? Maybe move one line up (before `commit_creds`) and add a comment that this line is for skipping `pop rbp`?

2025-03-24 16:06 UTC, matrizzo commented
Great writeup and code, thanks! This was very nice to review.

2025-03-24 16:07 UTC, merged