kernelctf: add CVE-2023-4015_cos
google/security-research pull request #140
Opened 2024-11-28 10:48 UTC by kungfulon

2025-03-14 15:11 UTC, koczkatamas requested changes
Hey,

This is just a quick code quality review. We're planning to review the submissions more deeply (actually understanding what the exploit does) in two weeks.

In general, the code quality looks good, no major concerns. I've left a few smaller comments.

We also have a draft style guide now. Please take a look and let us know if it's helpful for understanding our code quality expectations: https://google.github.io/security-research/kernelctf/style_guide.

Thanks for the submission and PR!

2025-03-14 15:11 UTC, koczkatamas commented on pocs/linux/kernelctf/CVE-2023-4015_cos/exploit/cos-105-17412.156.23/exploit.c
> +    fake_expr->ops = (struct nft_expr_ops *)(heap + 0x88 - 0x28); // offset 0x88 of fake rule <=> expr->ops->deactivate (offset 0x28 of expr->ops)
Do I understand correctly, that you selected the offset 0x88 based on where was free space in the ROP chain and 0x28 is the offset of `nft_expr_ops`'s `deactivate` field?

Can you use `#define NFT_EXPR_OPS_OFFS_DEACTIVATE 0x28` and use that macro?

And also move 0x88 into a variable (e.g. `deactivate_offset`) or define and set the JOP gadget via `rop[deactivate_offset/8] = vmlinux + PUSH_RSI_JMP_QWORD_PTR_RSI_F` instead of `*rop++ = vmlinux + PUSH_RSI_JMP_QWORD_PTR_RSI_F;`, so the connection is more clear?

More info is in [our style guide](https://google.github.io/security-research/kernelctf/style_guide#approach-2).

2025-03-14 15:11 UTC, koczkatamas commented on pocs/linux/kernelctf/CVE-2023-4015_cos/exploit/cos-105-17412.156.23/exploit.c
> +    *rop++ = vmlinux + PUSH_RSI_JMP_QWORD_PTR_RSI_F; // jop gadget, put here because this space is unused
Comment here where the RSI pointer points to (fake `nft_expr`?).

2025-03-14 15:11 UTC, koczkatamas commented on pocs/linux/kernelctf/CVE-2023-4015_cos/exploit/cos-105-17412.156.23/exploit.c
> +static int dump_expr_leak_vmlinux(expr e, void *dat) {
Nothing serious, but here the unused `dat` argument is a bit similar to the one used below (`data`), maybe consider renaming `dat` into `unused_` or something similar to make intention more clear.

2025-03-26 02:09 UTC, chanijindal1 requested changes
Thanks for the PR. Requested a couple extra comments where I thought it wasn't as easy to follow along from just the code.

2025-03-26 02:09 UTC, chanijindal1 commented on pocs/linux/kernelctf/CVE-2023-4015_cos/exploit/cos-105-17412.156.23/exploit.c
> +static int trigger_uaf() {
Could you add some comments to this function so it's easier to follow along in reading the bug trigger? E.g. create a chain X with use count 1.   Reference an invalid chain causing a rollback triggering the bug. Etc

2025-03-26 02:09 UTC, chanijindal1 commented on pocs/linux/kernelctf/CVE-2023-4015_cos/exploit/cos-105-17412.156.23/exploit.c
> +    for (int z = 0; z < SPRAY_BATCHES; ++z) {
Could you add a comment specifying what you are reclaiming with?

2025-05-12 03:11 UTC, kungfulon commented on pocs/linux/kernelctf/CVE-2023-4015_cos/exploit/cos-105-17412.156.23/exploit.c
> +void monke() {
Changed.

2025-05-12 03:11 UTC, kungfulon commented on pocs/linux/kernelctf/CVE-2023-4015_cos/exploit/cos-105-17412.156.23/exploit.c
> +    // INFO("Start callback: rseq = %d, seq = %d", rseq, seq);
Removed the comments.

2025-05-12 03:12 UTC, kungfulon commented on pocs/linux/kernelctf/CVE-2023-4015_cos/exploit/cos-105-17412.156.23/exploit.c
> +    fake_expr->ops = (struct nft_expr_ops *)(heap + 0x88 - 0x28); // offset 0x88 of fake rule <=> expr->ops->deactivate (offset 0x28 of expr->ops)
Defined the magic constants, can you check if it's sufficent?

2025-05-12 03:12 UTC, kungfulon commented on pocs/linux/kernelctf/CVE-2023-4015_cos/exploit/cos-105-17412.156.23/exploit.c
> +    *rop++ = vmlinux + PUSH_RSI_JMP_QWORD_PTR_RSI_F; // jop gadget, put here because this space is unused
Commented it.

2025-05-12 03:12 UTC, kungfulon commented on pocs/linux/kernelctf/CVE-2023-4015_cos/exploit/cos-105-17412.156.23/exploit.c
> +static int dump_expr_leak_vmlinux(expr e, void *dat) {
Changed to _unused.

2025-05-12 03:12 UTC, kungfulon commented on pocs/linux/kernelctf/CVE-2023-4015_cos/exploit/cos-105-17412.156.23/exploit.c
> +static int trigger_uaf() {
Added comments about c_free->use.

2025-05-12 03:13 UTC, kungfulon commented on pocs/linux/kernelctf/CVE-2023-4015_cos/exploit/cos-105-17412.156.23/exploit.c
> +    for (int z = 0; z < SPRAY_BATCHES; ++z) {
Added comments above this block about using nft_rule to reclaim the freed nft_chain.

2025-06-16 10:10 UTC, merged