Add kernelCTF CVE-2023-31436
google/security-research pull request #34
Opened 2023-07-24 08:05 UTC by liona24

2023-08-24 13:12 UTC, koczkatamas requested changes
We switched JSON schema version, please accept these changes to make the PR check succeed.

2023-08-24 13:12 UTC, koczkatamas commented on pocs/linux/kernelctf/CVE-2023-31436_mitigation/metadata.json
> +    "submission_id": "exp52",
In v2, this is an array:
```suggestion
    "submission_ids": ["exp52"],
```

2023-08-25 19:00 UTC, liona24 commented
Hey. Thanks for the update. My Makefile was using a slightly different target, so I fixed that. The exploit is using side channels for KASLR bypass. This does not appear to be working on the runner, does however work on the real instances. (tbh I haven't checked in a while, where there any infra changes?). Any suggestions on how to proceed here? I can have a closer look in a week or so.

2023-09-01 13:38 UTC, liona24 commented
So I checked again, the cache timing side channel works fine on the real instance. Both use QEMUs `-cpu host`, not sure what is underneath here.

Would KASLR disabled be an option for the CI job? As far as the CTF is concerned KASLR bruteforce is a valid strategy anyway, so you probably do not want such submissions to spam your runner too.

Also the CLA check is failing because apparently you (@koczkatamas  are not approved as a contributor and we shared some commits.

2023-09-01 14:42 UTC, koczkatamas commented
Hey!

Yeah, we will provide an option to disable KASLR. When it's ready (ETA:
next week), I will comment here.

On Fri, Sep 1, 2023, 15:38 liona24 ***@***.***> wrote:

> Reopened #34 <https://github.com/google/security-research/pull/34>.
>
> —
> Reply to this email directly, view it on GitHub
> <https://github.com/google/security-research/pull/34#event-10257437128>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/AAT4XUTUVAZVKQ5EL4DERJDXYHQN5ANCNFSM6AAAAAA2VGHKII>
> .
> You are receiving this because you were mentioned.Message ID:
> ***@***.***>
>

2023-09-17 01:17 UTC, koczkatamas commented
Implemented, KASLR base will be supplied as the first argument to `./exploit`. Example full command line: `su user -c '/tmp/exp/exploit ffffffff8a000000'`.

You need to change to the v3 metadata schema and modify the exploits node to this:

```json
    "exploits": {
        "mitigation-6.1": {
            "uses": ["userns"],
            "stability_notes": "5% success rate",
            "requires_separate_kaslr_leak": true
        }
    }
```

See the full modified file here: https://github.com/koczkatamas2/security-research/pull/1/files#diff-a3e5b8f8744c0ae7ff2ed99f0c28cb0a940bf5b6964a86eeecc0fa42d19bdd6d

2023-09-18 08:39 UTC, liona24 commented
Alright thank you very much. The only thing missing now is the CLA check because of the co-authored commits.

2023-09-20 17:51 UTC, merged