Add kernelCTF CVE-2023-3776
google/security-research pull request #49
Opened 2023-09-08 07:33 UTC by d4em0n

2023-11-14 03:38 UTC, d4em0n commented
@koczkatamas we fix the comments already

2023-11-29 14:41 UTC, koczkatamas requested changes
Hey! I've made a few change request. Please take a look at the individual comments and make the changes accordingly. Thank you!

2023-11-29 14:41 UTC, koczkatamas commented on pocs/linux/kernelctf/CVE-2023-3776_cos_mitigation/exploit/mitigation-6.1/poc.c
> +    int sp = socket(0x10ul, 3ul, 0xc); // later use this socket to spray struct ctnetlink_filter
Please use enum names instead of values (AF_NETLINK, SOCK_RAW, NETLINK_NETFILTER).

2023-11-29 14:41 UTC, koczkatamas commented on pocs/linux/kernelctf/CVE-2023-3776_cos_mitigation/exploit/mitigation-6.1/poc.c
> +size_t payment[] = {
Please use a more expressive variable name, for example `netlink_filter_payload` as there are multiple payloads are used in the exploit and it's easier to confuse them with eachother.

2023-11-29 14:41 UTC, koczkatamas commented on pocs/linux/kernelctf/CVE-2023-3776_cos_mitigation/exploit/mitigation-6.1/poc.c
> +    0x0201010100000024, 0x0000000000000000, 0x0008000800000000, 0x0015000858df0300, 0x00feffff};
Please make a comment here how you generated this payload. Optionally if there is a documentation to this structure format, it can be added as well.

It seems IIUC that you are using `CTA_MARK` (`0x08`) and `CTA_MARK_MASK` (`0x15`) attributes to set `ctnetlink_filter.mark` field (at offset `0x60`) to `0xfffffe000003df58` (with two uint32 writes).

Relevant `pahole -EC ctnetlink_filter mitigation-6.1-v2/vmlinux`:
```
struct ctnetlink_filter {
...
        struct ctnetlink_filter_u32 {
                /* typedef u32 -> __u32 */ unsigned int       val;                       /*    96     4 */
                /* typedef u32 -> __u32 */ unsigned int       mask;                      /*   100     4 */
        } mark; /*    96     8 */
...
};
```

Please add comment where the offset (`0x60`) and address (`0xfffffe000003df58`) comes from.

Relevant comment from the other exploit:
```
/* Try to overwrite struct drr_class's qdisc at offset 0x60 */
/* That address is at CPU#1 cpu_entry_area's entry_stack_page (stack address) while it try to push r15 in function error_entry*/
*(size_t*)&payload[0x60] = 0xfffffe000003df58;
```

2023-11-29 14:41 UTC, koczkatamas commented on pocs/linux/kernelctf/CVE-2023-3776_cos_mitigation/docs/exploit.md
> +	err = ctnetlink_parse_zone(cda[CTA_ZONE], &filter->zone);
It seems (see my other `ctnetlink_filter` comment), that the payload is stored at offset `0x60` which is the `mark` field which comes from `CTA_MARK` and `CTA_MARK_MASK` and not `CTA_ZONE` or `CTA_FILTER`.

If the above is correct, then please update the writeup to correctly reference the relevant code path 
 (otherwise it is misleading):
```
	err = ctnetlink_filter_parse_mark(&filter->mark, cda);
	if (err)
		goto err_filter;
```

Please also mention that this technique requires `CONFIG_NF_CONNTRACK_MARK` (+`CONFIG_NETFILTER_ADVANCED` + `CONFIG_NETFILTER`) and allows 8-byte overwrite at offset 0x60.

2023-11-30 03:36 UTC, d4em0n commented on pocs/linux/kernelctf/CVE-2023-3776_cos_mitigation/exploit/mitigation-6.1/poc.c
> +size_t payment[] = {
Done

2023-11-30 03:36 UTC, d4em0n commented on pocs/linux/kernelctf/CVE-2023-3776_cos_mitigation/docs/exploit.md
> +	err = ctnetlink_parse_zone(cda[CTA_ZONE], &filter->zone);
Fixed

2023-11-30 20:06 UTC, koczkatamas reviewed
Hey! Thanks for the changes! Meanwhile I asked 3 additional questions (see below), please take a quick look, but otherwise looks good! Thanks!

2023-11-30 22:53 UTC, d4em0n commented on pocs/linux/kernelctf/CVE-2023-3776_cos_mitigation/docs/exploit.md
> +Because CONFIG_KMALLOC_SPLIT_VARSIZE is enable, we need to find a struct we can spray in kmalloc-128 fixed cache. We found out `struct ctnetlink_filter` is in the right cache. We can spray it and put
yes, I think it should work for COS too. it was discovered later. The thing is, this object is immediately freed in the same allocation path it will make somewhat unreliable than the sendmsg spray, but this is enough to overwrite the field that we want.

2023-11-30 22:56 UTC, d4em0n commented on pocs/linux/kernelctf/CVE-2023-3776_cos_mitigation/docs/exploit.md
> +Snippet code if we use drr_class as target object as target object.
In the making of this exploit, we can choose another "class" with another size that fits into some fixed size objects for spray control, we found `ctnetlink_filter` in fixed size cache that fits with `drr_class`'s size.

2023-11-30 22:58 UTC, d4em0n commented on pocs/linux/kernelctf/CVE-2023-3776_cos_mitigation/exploit/cos-93-16623.341.29/poc.c
> +        write(sfd[i][1], buf, 0x1000);
We need to make socket send buffer is full, so the kernel will sleep in the 2nd sendmsg call after it allocates spray object from msg control data.
https://elixir.bootlin.com/linux/latest/source/net/unix/af_unix.c#L1953

2024-01-11 16:06 UTC, koczkatamas reviewed
Looks good, thanks!

2024-01-11 16:06 UTC, merged