Add kernelCTF CVE-2023-3776 (lts)
google/security-research pull request #50
Opened 2023-09-08 07:56 UTC by d4em0n

2023-10-27 12:05 UTC, koczkatamas requested changes
Hey! I've made some comments, can you please take a look and made the appropriate changes, add more explanations?

We are trying to make the submissions as understandable as possible, so it makes more easily for the community to learn from them!

Thank you!

2023-10-30 02:46 UTC, st424204 commented on pocs/linux/kernelctf/CVE-2023-3776_lts/exploit/lts-6.1.36/poc.c
> +                SYSCHK(setsockopt(fd[0], SOL_SOCKET, 26, &prog, sizeof(prog)));
Done

2023-10-30 02:47 UTC, st424204 commented on pocs/linux/kernelctf/CVE-2023-3776_lts/exploit/lts-6.1.36/poc.c
> +    read(stopfd[1], buf, 0x10);
Fixed inconsistent

2023-10-30 02:48 UTC, st424204 commented on pocs/linux/kernelctf/CVE-2023-3776_lts/exploit/lts-6.1.36/poc.c
> +        {.code = BPF_LD + BPF_K, .k = 0xb3909090},
Add more comment to explain 0xb3909090

2023-10-30 02:51 UTC, st424204 commented on pocs/linux/kernelctf/CVE-2023-3776_lts/exploit/lts-6.1.36/poc.c
> +    *(size_t *)0 = 0;
Add comment to tell about it

2023-10-30 02:51 UTC, st424204 commented on pocs/linux/kernelctf/CVE-2023-3776_lts/exploit/lts-6.1.36/poc.c
> +    for (int i = 0; i < 0x200; i++)
done

2023-10-30 02:54 UTC, st424204 commented on pocs/linux/kernelctf/CVE-2023-3776_lts/exploit/lts-6.1.36/poc.c
> +    for(int i=0x40;i<0x80;i+=0x8)
Fix this part of code. It used to target other struct than drr_class, overwriting mulitple places is convenient for us to switch other target struct

2023-10-30 02:54 UTC, st424204 commented on pocs/linux/kernelctf/CVE-2023-3776_lts/exploit/lts-6.1.36/poc.c
> +    SYSCHK(sendto(c, buf, 0x10, 0, (void *)&addr, sizeof(addr)));
It's not matter and I have added comment to explain what ths code trigger

2023-10-30 02:54 UTC, st424204 commented on pocs/linux/kernelctf/CVE-2023-3776_lts/exploit/lts-6.1.36/poc.c
> +        foo(rop);
done

2023-10-30 03:41 UTC, st424204 commented on pocs/linux/kernelctf/CVE-2023-3776_lts/exploit/lts-6.1.36/root.c
> +	system("cat /flag;echo o>/proc/sysrq-trigger");
Get flag and poweroff immediately to boost next round try in PR verification workflow

2023-10-30 03:43 UTC, st424204 commented on pocs/linux/kernelctf/CVE-2023-3776_lts/exploit/lts-6.1.36/poc.c
> +    rop[0] = 0xffffffffcc000000 - 0x800;
we spray eBPF multiple times and summarize it's often near in this page.
It's more reliabe we choose address in the middle of the page

2023-10-30 04:26 UTC, d4em0n commented on pocs/linux/kernelctf/CVE-2023-3776_lts/exploit/lts-6.1.36/poc.c
> +// the payload generated from `tc class delete dev lo classid 1:10`
added command to generate payload + reference for readers

2023-10-30 06:06 UTC, st424204 commented on pocs/linux/kernelctf/CVE-2023-3776_lts/exploit/lts-6.1.36/poc.c
> +int sc(void)
In current environment, the max instructions in a program is near 0x900 and we test 0x900 instructions * 0x50 forks * 0x100 sockets * 4 = 180 MB is enough large to spray and worked reliably

2023-10-30 06:06 UTC, st424204 commented on pocs/linux/kernelctf/CVE-2023-3776_lts/exploit/lts-6.1.36/poc.c
> +            *(size_t*)&payload[i] = 0xfffffe000003df58; //cpu_entry_area fixed kernel address
That address is at CPU#1 cpu_entry_area's entry_stack_page (stack address) while it try to push r15 in function error_entry

2023-10-30 06:27 UTC, d4em0n commented
Hi, thanks for the comment.
We will fix the rest of our PRs after this one is merged because it's similar.

2023-11-13 15:10 UTC, koczkatamas approved these changes

2023-11-13 15:11 UTC, merged