kernelCTF: added CVE-2024-1086 lts mitigation
google/security-research pull request #96
Opened 2024-04-03 15:40 UTC by Notselwyn

2024-07-23 15:49 UTC, koczkatamas requested changes
I've made a few suggestions, please take a look!

2024-07-23 15:56 UTC, matrizzo commented
It would be useful to link to your blog post in the writeup (https://pwning.tech/nftables/) because some techniques like dirty pagedirectory are explained in more detail there.
Also specifically regarding dirty PGD, I think the explanation (both here in the PR and on your website) is a bit hard to understand, maybe instead of [this diagram](https://pwning.tech/content/images/2024/03/dirtypagedirectory.svg) you could have something where you show that the PUD points back to itself?

2024-07-29 12:03 UTC, koczkatamas commented on pocs/linux/kernelctf/CVE-2024-1086_lts_mitigation/docs/exploit.md
> +In order to bypass `CONFIG_FREELIST_HARDENED`'s naive double-free detection, we simply allocate an skb (remove from the freelist) before the double-free, which we free (append to the freelist) in bet
Can you use relative paths, e.g. `../exploit/lts-6.1.72/src/exploit.c#L362` instead of https://github.com/Notselwyn/security-research/blob/a4da96327b8bd940e4d5ae0c565d060b11e54ce7/pocs/linux/kernelctf/CVE-2024-1086_lts_mitigation/exploit/lts-6.1.72/src/exploit.c#L362, GH should be able to handle this link format after we merge the change.

Thanks!

2024-07-29 12:04 UTC, koczkatamas commented
> Done 👍 @koczkatamas can I resolve the changes you requested?

Thanks! I've made one comment.

The review will be continued by @matrizzo, but is out-of-office this week, so probably next week earliest.

2024-09-07 20:50 UTC, HerrSpace commented
@matrizzo This seems to have fallen through the cracks. :^)

2024-09-09 11:02 UTC, koczkatamas commented
Hey! Sorry for the long process...

Meanwhile you could please take a look at another nftables submissions (we got a ton) and how did they solve that they don't include the Linux kernel header files?

This also needs to be resolved before we can merge the commit.

I will ping @matrizzo to try to finish the review this week.

2024-09-11 10:27 UTC, koczkatamas commented on pocs/linux/kernelctf/CVE-2024-1086_lts_mitigation/docs/novel-techniques.md
> +TODO: increase description granularity for techniques proven to be novel.
Could you please still look into if you can exclude the header files?

There are several other nftables submissions in the repo and in the PRs. Is there anything different in your submission which does not make this possible?

2024-09-12 12:31 UTC, matrizzo commented
Looks good, thanks for the submission

2024-09-12 13:04 UTC, merged